const fs = require('fs');
const path = require('path');
const target = path.join(__dirname, '..', 'insuwork', 'product-lineups', 'data', '2026-09.json');
const data = JSON.parse(fs.readFileSync(target, 'utf8'));
const additions = [
  {company:'흥국화재',type:'nonlife',source:'★흥국화재 GA소식지 26.9월호 최종본(260826).pdf',products:[{name:'흥Good 모두 담은 암보험 PLUS',group:'암',point:'암 보장 상품',page:16},{name:'든든한 3N5 간편종합보험',group:'건강',point:'3N5 간편심사 종합보험',page:16},{name:'플러스간편치매간병보험',group:'치매·간병',point:'간편심사 치매·간병보험',page:16},{name:'The편한 운전자상해보험',group:'운전자',point:'운전자·상해보험',page:16}]},
  {company:'NH농협손해보험',type:'nonlife',source:'농협손보2609GA소식지 심의필_pdf.pdf',products:[{name:'NH 5.N.5 굿플러스 건강보험(1040)',group:'건강',point:'5.N.5 건강보험',page:18},{name:'NH헤아림 3.10.10 건강보험',group:'건강',point:'3.10.10 간편심사 건강보험',page:18},{name:'NH헤아림355 건강보험',group:'건강',point:'3.5.5 간편심사 건강보험',page:18},{name:'NH아이맘헤아림 어린이보험',group:'자녀',point:'어린이보험',page:18}]},
  {company:'삼성화재',type:'nonlife',source:'260827_삼성화재 9월 GA소식지(CR완료)(펼침면).pdf',products:[{name:'마이스타 0515',group:'자녀',point:'소식지 상품 라인업 수록',page:16},{name:'오토바이 운전자보험 일반형',group:'운전자',point:'운전자 비용담보·상해보장',page:15}]}
];
additions.forEach(function(c){const i=data.companies.findIndex(function(x){return x.company===c.company;});if(i<0)data.companies.push(c);else data.companies[i]=c;});
function uniq(a){return Array.from(new Set(a.filter(Boolean)));}
function classify(p){const t=[p.name,p.group,p.point].join(' ');let purpose='건강·질병';if(/치매|간병|장기요양/.test(t))purpose='치매·간병';else if(/종신|정기|경영인/.test(t))purpose='사망보장';else if(/연금|변액|달러/.test(t))purpose='노후·자산';else if(/어린이|자녀|여성|치아|운전자|상해/.test(t))purpose='가족·생활';const u=[];if(/초경증/.test(t))u.push('초경증');if(/간편|3[.N]\d|3\.\d+\.\d+|5\.N\.5|5N5/.test(t))u.push('간편심사');if(/건강체|건강고지/.test(t))u.push('건강고지');if(!u.length&&!/플랜/.test(t))u.push('확인 필요');let renewal='확인 필요';if(/비갱신/.test(t))renewal='비갱신형';else if(/갱신/.test(t))renewal='갱신형';const entityType=/플랜|라인/.test(p.name)||/플랜군|플랜/.test(p.point)?'plan':'product';return Object.assign({},p,{id:p.id||p.name.replace(/[^0-9A-Za-z가-힣]+/g,'-').replace(/^-|-$/g,'').toLowerCase(),entityType:p.entityType||entityType,purpose:p.purpose||purpose,underwriting:uniq(p.underwriting||u),renewal:p.renewal||renewal,target:uniq(p.target||[/어린이|자녀/.test(t)?'어린이':'',/여성/.test(t)?'여성':'',/경영인/.test(t)?'경영인':'']),currency:/달러/.test(t)?'달러':(/변액/.test(t)?'변액':''),confidence:p.confidence||(entityType==='plan'?'needs-review':'confirmed')});}
data.schemaVersion=2;data.updatedAt='2026-09-01';data.reviewPolicy='소식지에 명시된 값만 확정하고, 미기재 값은 확인 필요로 표시';data.companies.forEach(function(c){c.products=c.products.map(classify);});data.companies.sort(function(a,b){if(a.type!==b.type)return a.type==='nonlife'?-1:1;return a.company.localeCompare(b.company,'ko');});fs.writeFileSync(target,JSON.stringify(data,null,2)+'\n','utf8');console.log('companies='+data.companies.length+' entries='+data.companies.reduce(function(n,c){return n+c.products.length;},0));
