const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const owner='98c5f4f9-10c1-4ee1-a656-5c2ca63239fd';
const source=fs.readFileSync('insuwork/ledger.js','utf8');
function boot(id,token){const calls=[];const context={window:{AppState:{userId:id},db:{getToken:()=>token,fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>[]};}}},localStorage:{getItem:()=>null},sessionStorage:{getItem:()=>null},document:{addEventListener:()=>{}},console};vm.createContext(context);vm.runInContext(source.replace('window.OSInsuworkLedger={','window.testLedger={valid,total,request,scope};window.OSInsuworkLedger={'),context);return {...context,calls};}
test('only exact owner with session can open; anonymous and other accounts deny without requests',async()=>{for(const [id,token] of [[null,null],[owner,null],['other','session']]){const c=boot(id,token);assert.equal(c.window._canSeeInsuworkLedger(),false);assert.match(c.window.OSInsuworkLedger.html(),/전용/);await assert.rejects(c.window.testLedger.request(''));assert.equal(c.calls.length,0);}assert.equal(boot(owner,'session').window._canSeeInsuworkLedger(),true);});
test('reads scoped private ledger only; no token or personal data in URL',async()=>{const c=boot(owner,'session');await c.window.testLedger.request('?'+c.window.testLedger.scope());assert.match(c.calls[0].url,/owner_id=eq\.98c5/);assert.match(c.calls[0].url,/visibility=eq.private/);assert.match(c.calls[0].url,/setting_key=eq.personal_ledger_v1/);assert.match(c.calls[0].url,/deleted_at=is.null/);});
test('reject invalid calendar dates, decimals, unsafe amounts and unknown types',()=>{const {valid}=boot(owner,'session').window.testLedger;const entry={date:'2026-08-31',type:'expense',amount:12000,category:'식비',memo:'점심'};assert.equal(valid(entry),true);for(const change of [{date:'2026-02-30'},{amount:1.5},{amount:-1},{amount:Infinity},{amount:1e16},{type:'transfer'},{category:'<script>'},{memo:'x'.repeat(121)}])assert.equal(valid({...entry,...change}),false);});
test('income minus spending is net flow, zero and large integer totals stay exact',()=>{const {total}=boot(owner,'session').window.testLedger;assert.equal(total([]).income,0);const sums=total([{legacy_payload:{entry:{type:'income',amount:4000000}}},{legacy_payload:{entry:{type:'expense',amount:15000}}},{legacy_payload:{entry:{type:'expense',amount:85000}}}]);assert.equal(sums.income-sums.expense,3900000);});
function forecast(){const c=boot(owner,'session');vm.createContext(c);vm.runInContext(source.replace('window.OSInsuworkLedger={','window.planTest={validPlan,shiftMonth,dueDate,projections,forecastSummary};window.OSInsuworkLedger={'),c);return c.window.planTest;}
function plan(changes={}){return {id:'plan-1',legacy_payload:{plan:{name:'관리비',amount:200000,day:31,start:'2026-08',end:'',frequency:'monthly',date:'2026-08-31',versions:[],paid:{},...changes}}};}
test('monthly projection handles year rollover and leap/short month ends without generating rows',()=>{const f=forecast(),r=plan({start:'2024-01'});assert.equal(f.dueDate('2024-02',31),'2024-02-29');assert.equal(f.dueDate('2026-02',31),'2026-02-28');assert.equal(f.shiftMonth('2026-12',1),'2027-01');assert.equal(f.projections([r],'2026-09')[0].date,'2026-09-30');assert.equal(r.legacy_payload.plan.paid['2026-09'],undefined);});
test('start/end and one-off rules exclude unrelated months but preserve paid history',()=>{const f=forecast();assert.equal(f.projections([plan()],'2026-07').length,0);assert.equal(f.projections([plan({end:'2026-08'})],'2026-09').length,0);assert.equal(f.projections([plan({frequency:'once'})],'2026-09').length,0);assert.equal(f.projections([plan({end:'2026-08',paid:{'2026-09':{amount:210000,date:'2026-08-31'}}})],'2026-09').length,1);});
test('paid actual replaces estimate in expected total and only unpaid amounts remain',()=>{const f=forecast(),a=plan({paid:{'2026-08':{amount:180000,date:'2026-08-31'}}}),b=plan({amount:50000});b.id='plan-2';const sum=f.forecastSummary(f.projections([a,b],'2026-08'));assert.equal(sum.expected,230000);assert.equal(sum.paid,180000);assert.equal(sum.remaining,50000);assert.equal(f.forecastSummary(f.projections([a,b],'2026-09')).remaining,250000);});
test('future amount revision leaves earlier expectations and completed amounts intact',()=>{const f=forecast(),r=plan({versions:[{from:'2026-09',name:'관리비',amount:220000,day:25}],paid:{'2026-08':{amount:190000,date:'2026-08-31'}}});assert.equal(f.projections([r],'2026-08')[0].estimate,200000);assert.equal(f.projections([r],'2026-09')[0].estimate,220000);assert.equal(f.projections([r],'2026-09')[0].date,'2026-09-25');assert.equal(f.forecastSummary(f.projections([r],'2026-08')).paid,190000);assert.equal(f.validPlan(r.legacy_payload.plan),true);assert.equal(f.validPlan({...r.legacy_payload.plan,day:0}),false);});
