const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function setup(service={}){let dialog=null;const status={textContent:''},root={querySelector:()=>dialog,appendChild(d){dialog=d}};const document={addEventListener(){},querySelector:s=>s==='#v-insuwork'?root:dialog,querySelectorAll:()=>[],createElement:()=>({setAttribute(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false},remove(){dialog=null},querySelector:()=>status})};const context={window:{OSInsuwork:service},document,crypto:webcrypto,console,fetch:async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('data/coverage_synonyms.json','utf8'))})};vm.createContext(context);vm.runInContext(fs.readFileSync('js/insuwork-coverage.js','utf8').replace('window.OSInsuworkCoverage = exposed;','window.OSInsuworkCoverage = exposed;window.testing={mergeImportedRecord,recordFromStructured,loadCoverageSynonyms,coverageMatchKey,draft};'),context);return {api:context.window.testing,ui:context.window.OSInsuworkCoverage,dialog:()=>dialog,status};}
const row=(id,section,name,total='',group='')=>({id,section,group,name,total,values:{}});
test('overview uses actual enrolled amount, no fake company; multiple unknown product columns retained',()=>{const {api}=setup();const result=api.recordFromStructured({products:[{company:'보험사',product:'상품명'}],rows:[{section:'운전',name:'교통사고 벌금(대인)',recommended:'5000만',values:['3000만']}]},'sample.png','png');assert.equal(result.products.length,0);assert.equal(result.rows[0].total,'3000만');assert.equal(result.rows[0].recommended,'5000만');const multiple=api.recordFromStructured({products:[{},{}],rows:[{name:'담보',values:['100','200']}]},'sample.png','png');assert.equal(multiple.products.length,2);assert.deepEqual(Object.values(multiple.rows[0].values),['100','200']);});
test('대인/대물, 장해 percentages and caregiver support/use never overwrite one another',async()=>{const {api}=setup();await api.loadCoverageSynonyms();for(const [a,b] of [['교통사고 벌금(대인)','교통사고 벌금(대물)'],['질병후유장해(50% 이상)','질병후유장해(80% 이상)'],['간병인지원 질병입원일당','간병인사용 질병입원일당']])assert.notEqual(api.coverageMatchKey(a),api.coverageMatchKey(b));const base={products:[],rows:[row('a','운전자','교통사고 벌금(대인)'),row('b','운전자','교통사고 벌금(대물)')]};const result=api.mergeImportedRecord(base,{products:[],rows:[row('c','운전','교통사고 벌금(대인)','3000만'),row('d','운전','교통사고 벌금(대물)','500만')]});assert.equal(result.rows.length,2);assert.equal(result.rows.find(r=>r.id==='a').total,'3000만');assert.equal(result.rows.find(r=>r.id==='b').total,'500만');});
test('saved caregiver categories win; unspecified duration stays separate within existing category',async()=>{const {api}=setup();await api.loadCoverageSynonyms();const base={products:[],rows:[row('a','간병인','간호·간병통합서비스 질병입원일당(1~180일한)','','간호·간병통합서비스'),row('b','치매','경도·경증 치매_CDR 1점','','진단비'),row('c','장기요양','장기요양 진단비(1~2등급)','','진단비')]};const incoming={products:[],rows:[row('i','간병','질병간호·간병통합서비스사용일당','20만'),row('j','치매','치매 진단(경증)',''),row('k','치매','장기간병요양진단(1,2급)','100만')]};const result=api.mergeImportedRecord(base,incoming);assert.ok(result.rows.every(r=>!['간병','치매간병','치매·간병'].includes(r.section)));assert.equal(result.rows.find(r=>r.total==='20만').section,'간병인');assert.equal(result.rows.find(r=>r.id==='a').total,'');assert.equal(result.rows.find(r=>r.total==='100만').section,'장기요양');assert.equal(api.mergeImportedRecord(result,incoming).rows.length,result.rows.length);});
test('loading spans extraction and save, blocks duplicate import and cleans up on failure',async()=>{let finish,saveFinish,calls=0,errors=[];const {ui,api,dialog,status}=setup({extractCoverageFile(){calls++;return new Promise(r=>finish=r)},saveCoverageWorkspaceDraft:r=>new Promise(resolve=>saveFinish=()=>resolve(r)),rerenderCoverageWorkspace(){},coverageError:e=>errors.push(e)});const key='__coverage_workspace__';ui.reset(key,{products:[],rows:[row('base','간병인','기존담보')]});const input={files:[{name:'sample.png'}],value:'sample.png'};const pending=ui.importFile(key,input);assert.equal(dialog().open,true);ui.importFile(key,{files:input.files,value:'duplicate'});await new Promise(r=>setImmediate(r));assert.equal(calls,1);finish({products:[],rows:[{section:'간병',name:'새담보',total:'20만'}]});await new Promise(r=>setImmediate(r));assert.match(status.textContent,/저장/);assert.equal(dialog().open,true);saveFinish();await pending;assert.equal(dialog(),null);assert.equal(input.value,'');assert.equal(errors.length,0);
const failure=setup({extractCoverageFile(){throw Error('분석 실패')},coverageError:e=>errors.push(e)});await failure.ui.importFile(key,{files:input.files,value:'sample.png'});assert.equal(failure.dialog(),null);assert.equal(errors.at(-1),'분석 실패');});
test('multiple imports save together and failure leaves previous draft untouched',async()=>{
let saves=0,savedFiles;
const good=setup({extractCoverageFile:async file=>({products:[{company:'보험사A',product:'상품A'}],rows:[{section:'암',name:'암 진단',values:['1000만']}]}),saveCoverageWorkspaceDraft:async(r,files)=>{saves++;savedFiles=files;return r},rerenderCoverageWorkspace(){},coverageError:e=>{throw Error(e)}});
good.ui.reset('__coverage_workspace__',{products:[],rows:[]});await good.ui.importFile('__coverage_workspace__',{files:[{name:'one.png'},{name:'two.png'}],value:'x'});
assert.equal(saves,1);assert.equal(savedFiles.length,2);assert.equal(good.api.draft('__coverage_workspace__').products.length,1);
let errors=[];const bad=setup({extractCoverageFile:async file=>{if(file.name==='two.png')throw Error('두 번째 실패');return {rows:[{section:'암',name:'암 진단',total:'1000만'}]}},saveCoverageWorkspaceDraft:async()=>{saves++},coverageError:e=>errors.push(e)});
bad.ui.reset('__coverage_workspace__',{products:[],rows:[row('original','암','기존담보')]});await bad.ui.importFile('__coverage_workspace__',{files:[{name:'one.png'},{name:'two.png'}],value:'x'});
assert.equal(saves,1);assert.equal(bad.api.draft('__coverage_workspace__').rows[0].id,'original');assert.deepEqual(errors,['두 번째 실패']);
});
