const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm'), {webcrypto} = require('node:crypto');
function setup(){const c={window:{},document:{addEventListener(){},querySelector(){return null}},crypto:webcrypto,console,fetch:async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('data/coverage_synonyms.json','utf8'))})};vm.createContext(c);vm.runInContext(fs.readFileSync('js/insuwork-coverage.js','utf8').replace('window.OSInsuworkCoverage = exposed;','window.testing={parseKbPdf,loadCoverageSynonyms,mergeImportedRecord,normalize};'),c);return c.window.testing;}
const item=(str,x,y)=>({str,transform:[9,0,0,9,x,y]});
function page(number,rows){return {width:595,height:842,items:[item('상품별 가입담보상세',135,801),item('테스트',32,801),item('보험사A',42,752),item('가입일자 : 2026-04-30',450,752),item('시험보험 (2604) ('+number+'/2)',42,728.5),item('월납/20년/90세만기',414,692),item('81,176',519,670),item('원',556,670),...rows.flatMap((r,i)=>[item(String(r[0]),38,629-i*17),item('정액',65,629-i*17),item(r[1],92,629-i*17),item(r[2],367,629-i*17),item(r[3],529,629-i*17)])]};}
const data=[page(1,[[1,'간편고지(3.N.5) 카티(CAR-T)항암약물허가치료비(최초1회한)(갱신형)','고액항암치료비','5,000만'],[2,'간편고지(3.N.5) 표적항암약물허가치료비(최초1회한)(갱신형)','고액항암치료비','2,000만'],[3,'간편고지(3.N.5) 항암세기조절방사선치료비(최초1회한)','고액항암치료비','2,000만'],[4,'간편고지(3.N.5) 항암양성자방사선치료비(최초1회한)','고액항암치료비','2,000만']]),page(2,[[5,'간편고지(3.N.5) 항암중입자방사선치료비(최초1회한)','기타 인보험(정액)담보','5,000만']])];
test('KB details replace summary, join continuation, retain individual treatments and evidence',async()=>{const a=setup();await a.loadCoverageSynonyms();const r=a.parseKbPdf([{items:[item('암수술비 300만 1,700만 충분',100,600)]},...data,...data],'report.pdf');assert.equal(r.products.length,1);assert.equal(r.rows.length,5);assert.equal(r.customerInfo.name,'테스트');assert.equal(r.products[0].premium,'81,176원');assert.ok(r.rows.every(x=>!x.name.includes('고액항암')&&x.sourceDetails.length===1));assert.equal(Object.values(r.rows.find(x=>x.name.includes('중입자')).values)[0],'5,000만');assert.equal(r.rows[0].sourceDetails[0].companyName.includes('갱신형'),true);});
test('KB outranks MyData in either order and after repeated import; template survives',async()=>{const a=setup();await a.loadCoverageSynonyms();const kb=a.parseKbPdf(data,'report.pdf');const template={products:[],rows:[{id:'template',section:'암',group:'치료비2',name:'표적항암약물치료비',values:{}}]};const my={products:[{id:'my',company:'보험사A',product:'시험보험 (2604)',premium:'1원'}],rows:[{id:'m',section:'암',name:'표적항암약물치료비',values:{my:'100만'}}]};let first=a.mergeImportedRecord(a.mergeImportedRecord(template,my),kb);assert.equal(first.rows.find(x=>x.id==='template').values[first.products[0].id],'2,000만');assert.equal(first.products[0].premium,'81,176원');assert.equal(first.rows.find(x=>x.id==='template').total,'2,000만');let reverse=a.mergeImportedRecord(a.mergeImportedRecord(template,kb),my);assert.equal(reverse.rows.length,5);assert.equal(reverse.rows.find(x=>x.id==='template').values[reverse.products[0].id],'2,000만');assert.equal(a.mergeImportedRecord(reverse,kb).rows.length,5);});
test('malformed recognized KB stops; other layouts return null for structured extraction',()=>{const a=setup();const invalid=page(1,[[1,'담보','기타','읽기실패']]);assert.throws(()=>a.parseKbPdf([invalid],'report.pdf'),/가입금액/);assert.equal(a.parseKbPdf([{items:[item('다른 PDF',10,10)]}],'report.pdf'),null);});

test('legacy noise is quarantined and KB combined silson maps to four existing template rows',async()=>{const a=setup();await a.loadCoverageSynonyms();const names=['상해 입원 의료비','질병 입원 의료비','상해 통원 의료비','질병 통원 의료비'];const base={rows:names.map((name,i)=>({id:'base'+i,section:'실손',group:'세대 확인',name,values:{}})).concat([{id:'bad',section:'실손',name:'질병입원의료비   만   억   충분',total:'5000',values:{}}]),products:[]};const kb={source:{provider:'kb-detail'},products:[{id:'p',company:'보험사A',product:'종합보험0505',contractDate:'2005-09-09',coverageAuthority:'kb-detail'}],rows:['입원','통원'].map((type,i)=>({id:'k'+i,section:'실손',name:'상해+질병(전체상해 및 전체질병을 포괄)'+type+'의료비',values:{p:i?'10만':'3000만'},valueSources:{p:'kb-detail'},sourceDetails:[{provider:'kb-detail',number:String(i)}]}))};const r=a.mergeImportedRecord(base,kb);assert.equal(r.rows.length,4);assert.equal(r.legacyRejectedRows.length,1);for(const row of r.rows){assert.match(row.id,/^base/);assert.equal(row.group,'1세대 실손');assert.equal(row.total,row.name.includes('입원')?'3,000만':'10만');assert.ok(row.sharedLimit);}assert.equal(a.normalize(r).legacyRejectedRows.length,1);assert.equal(a.mergeImportedRecord(r,kb).rows.length,4);});
test('mixed customer detail pages reject and ordinary unknown benefits remain visible',()=>{const a=setup();const mixed=JSON.parse(JSON.stringify(data));mixed[1].items.find(i=>i.str==='테스트').str='다른고객';assert.throws(()=>a.parseKbPdf(mixed,'report.pdf'),/서로 다른 고객/);assert.equal(a.normalize({rows:[{name:'새로운 담보',values:{},total:'500만'}]}).rows.length,1);});
