const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync('insuwork/ledger-sheet-core.js','utf8'),c);const core=c.OSLedgerSheetCore;
function row(estimate,extra={}){return {id:Math.random().toString(),kind:'expense',name:'항목',date:'2026-09-25',estimate:String(estimate),actual:'',paid:false,memo:'',...extra};}
test('numeric deadline accepts eight digits, preserves partial/invalid input and checks leap years',()=>{assert.equal(core.normalizeDate('20260925'),'2026-09-25');assert.equal(core.normalizeDate('20270105'),'2027-01-05');assert.equal(core.normalizeDate('20240229'),'2024-02-29');for(const value of ['20260229','20261301','20260931','202609','2026-09-25','2026/9/25',''])assert.equal(core.normalizeDate(value),value);const rows=[row(81930,{date:core.normalizeDate('20260925')})];assert.equal(core.summary(rows,core.calculate(rows),'2026-09').remaining,81930);assert.equal(core.calculate([row(81930,{date:core.normalizeDate('20260230')})]).error,true);});
test('arithmetic precedence, parentheses, comma numbers and rounded won',()=>{const a=core.calculate([row('=81930+5000'),row('=(100+50)*2/3'),row('229,760'),row('=10/3')]);assert.deepEqual(Array.from(a.rows,r=>r.estimate.value),[86930,100,229760,3]);});
test('cell references and SUM support dependencies without counting total rows twice',()=>{const rows=[row(81930),row(229760),row('=C2+C3'),row('=SUM(C2:C4)',{kind:'total'})],calc=core.calculate(rows);assert.equal(calc.rows[3].estimate.value,623380);assert.equal(core.summary(rows,calc,'2026-09').estimate,623380);});
test('cycles, zero division, bad references and executable text fail closed',()=>{for(const [expr,error] of [['=C2','#CYCLE!'],['=1/0','#DIV/0!'],['=C99','#REF!'],['=A2','#VALUE!'],['=fetch("x")','#FORMULA!'],['=1e9','#FORMULA!']]){const a=core.calculate([row(expr)]);assert.equal(a.rows[0].estimate.error,error);assert.equal(a.error,true);}assert.equal(core.calculate([row('=C3'),row('=C2')]).error,true);});
test('deletion adjusts range and references; missing referenced cell becomes visible REF error',()=>{let rows=[row(10),row(20),row(30),row('=SUM(C2:C4)',{kind:'total'})];let next=core.remove(rows,1);assert.equal(next[2].estimate,'=SUM(C2:C3)');assert.equal(core.calculate(next).rows[2].estimate.value,40);next=core.remove([row(10),row('=C2')],0);assert.equal(next[0].estimate,'=#REF!');assert.equal(core.calculate(next).error,true);});
test('row copy shifts relative references and resets paid state',()=>{const rows=[row(10),row('=C2*3',{paid:true,actual:'30'})];const copy=core.copy(rows,1,'copy');assert.equal(copy.estimate,'=C3*3');assert.equal(copy.actual,'');assert.equal(copy.paid,false);assert.equal(core.copy([row('=$C$2')],0,'copy').estimate,'=$C$2');});
test('monthly totals use deadlines and actual payment, incomplete rows never report false zero',()=>{const rows=[row(81930),row(229760,{date:'2026-10-25',paid:true,actual:'220000'}),row('=SUM(C2:C3)',{kind:'total',date:''})],calc=core.calculate(rows);assert.equal(core.summary(rows,calc,'2026-09').remaining,81930);assert.equal(core.summary(rows,calc,'2026-10').expected,220000);assert.equal(core.calculate([row(1,{date:'2026-02-30'})]).error,true);assert.equal(core.calculate([row(1,{paid:true})]).error,true);assert.equal(core.valid({version:1,rows:rows}),true);assert.equal(core.valid({version:1,rows:[rows[0],rows[0]]}),false);});
