const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function setup(workbook){const context={window:{XLSX:{read:()=>workbook,utils:{sheet_to_json:s=>s}},OSInsuwork:{coverageInsuranceAge:()=>39}},document:{addEventListener(){},querySelector(){return null}},crypto:webcrypto,queueMicrotask(){}};vm.createContext(context);vm.runInContext(fs.readFileSync('js/insuwork-coverage.js','utf8').replace('window.OSInsuworkCoverage = exposed;','window.OSInsuworkCoverage = exposed;window.helpers={extractedCustomerInfo,normalizedBirthDate,parseWorkbook,recordFromStructured,mergeImportedRecord};'),context);return {h:context.window.helpers,ui:context.window.OSInsuworkCoverage};}
test('BankSalad merged identity cell flows through workbook import, merge, rendering and serialization',()=>{
 const book={SheetNames:['보장'],Sheets:{보장:[['홍길동\n여성 1987년 12월 26일','','','','','','보험사'],['','','','','','','50000원'],['보장구분','주요특약','보장상태','연령대 평균','총 가입금액','금액차이','상품'],['암','일반암 진단비','보유','','1000만','','1000만']]}};
 const {h,ui}=setup(book);const parsed=h.parseWorkbook(null,'export.xlsx');assert.equal(parsed.customerInfo.name,'홍길동');assert.equal(parsed.customerInfo.birthDate,'1987-12-26');
 const merged=h.mergeImportedRecord({products:[],rows:[]},parsed);const html=ui.workspaceHtml(JSON.parse(JSON.stringify(merged)));assert.match(html,/value="홍길동"/);assert.match(html,/value="1987-12-26"/);assert.match(html,/보험나이 39세/);
});
test('filename can supply masked customer name; contract dates, age and password do not supply birth date',()=>{const {h}=setup();const info=h.extractedCustomerInfo(['보장기간 2015.04.07 ~ 2078.04.07','보험나이 39세','비밀번호 871226'],'박O롬님_보장진단_2026-08-27 오전 10-11.xlsx');assert.equal(info.name,'박O롬');assert.equal(info.birthDate,undefined);assert.equal(h.normalizedBirthDate('2025-02-30'),'');assert.equal(h.normalizedBirthDate('1987-12-**'),'');});
test('OCR identity survives structured conversion and fills missing fields without changing linked customer',()=>{const {h}=setup();const parsed=h.recordFromStructured({customerInfo:{name:'홍길동',birthDate:'1987.12.26'},products:[],rows:[]},'scan.png','png');const merged=h.mergeImportedRecord({customerInfo:{id:'existing',name:'홍길동'},products:[],rows:[]},parsed);assert.equal(merged.customerInfo.id,'existing');assert.equal(merged.customerInfo.birthDate,'1987-12-26');});
test('conflicting customers reject import without mutating existing identity',()=>{const {h}=setup();const base={customerInfo:{name:'홍길동',birthDate:'1987-12-26'},products:[],rows:[]};assert.throws(()=>h.mergeImportedRecord(base,{customerInfo:{name:'김다른'},products:[],rows:[]}),/서로 다른 고객/);assert.equal(base.customerInfo.name,'홍길동');});
