const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync('insuwork/ledger-sheet-core.js','utf8'),c);const core=c.OSLedgerSheetCore;
function row(estimate,extra={}){return {id:Math.random().toString(),kind:'expense',name:'항목',date:'2026-09-25',estimate:String(estimate),actual:'',paid:false,memo:'',...extra};}
test('month details match expected totals, include legacy and unfinished rows, and exclude totals/other months',()=>{const rows=[row(100,{name:'late',paid:true,actual:'80'}),row(20,{date:'2026-10-01'}),row('=SUM(C2:C3)',{kind:'total'}),row('',{name:'unfinished',date:'2026-09-20'})],calc=core.calculate(rows),legacy=[{id:'plan',name:'repeat',date:'2026-09-10',estimate:30,paid:null}];const details=core.monthDetails(rows,calc,'2026-09',legacy);assert.deepEqual(Array.from(details,d=>d.name),['repeat','unfinished','late']);assert.equal(details[0].source,'legacy');assert.equal(details[1].amount,null);assert.ok(details[1].error);assert.equal(details[2].index,0);assert.equal(details[2].amount,80);assert.equal(details.filter(d=>!d.error).reduce((n,d)=>n+d.amount,0),core.summary(rows,calc,'2026-09').expected+30);assert.equal(core.monthDetails(rows,calc,'2027-01',[]).length,0);});
test('item/date sorting is stable, puts blanks and totals last, and preserves formula rows',()=>{const rows=[row(10,{name:'나',date:'2026-10-10'}),row('=C2*3',{name:'가',date:'2026-09-10'}),row(0,{name:'',date:''}),row('=SUM(C2:C3)',{kind:'total'})],before=JSON.stringify(rows);assert.deepEqual(Array.from(core.sortedIndices(rows,'name','asc')),[1,0,2,3]);assert.deepEqual(Array.from(core.sortedIndices(rows,'name','desc')),[0,1,2,3]);assert.deepEqual(Array.from(core.sortedIndices(rows,'date','asc')),[1,0,2,3]);assert.deepEqual(Array.from(core.sortedIndices(rows,'date','desc')),[0,1,2,3]);assert.equal(JSON.stringify(rows),before);assert.equal(core.calculate(rows).rows[1].estimate.value,30);assert.equal(core.calculate(rows).rows[3].estimate.value,40);const same=[row(1),row(2)];assert.deepEqual(Array.from(core.sortedIndices(same,'name','desc')),[0,1]);});
test('unfinished October never hides September and completes automatically',()=>{const rows=[row(81930),row('',{date:'2026-10-10'})];let calc=core.calculate(rows);assert.equal(core.summary(rows,calc,'2026-09').error,false);assert.equal(core.summary(rows,calc,'2026-09').expected,81930);assert.equal(core.summary(rows,calc,'2026-10').error,true);assert.equal(core.summary(rows,calc,'2026-08').error,false);rows[1].estimate='229760';calc=core.calculate(rows);assert.equal(core.summary(rows,calc,'2026-10').error,false);assert.equal(core.summary(rows,calc,'2026-10').expected,229760);});
test('unassigned dates are explicit; total-only errors do not poison monthly expenses',()=>{const rows=[row(81930),row(10,{date:''}),row('=1/0',{kind:'total'})],calc=core.calculate(rows),sep=core.summary(rows,calc,'2026-09');assert.equal(sep.error,false);assert.equal(sep.unassigned,1);assert.equal(sep.expected,81930);assert.equal(core.summary(rows,calc).error,true);});
test('bad dates and cross-month formula errors affect only their expense months',()=>{const rows=[row('=1/0'),row('=C2',{date:'2026-10-10'}),row(20,{date:'2026-11-31'}),row(30,{date:'2026-12-10'})],calc=core.calculate(rows);for(const m of ['2026-09','2026-10','2026-11'])assert.equal(core.summary(rows,calc,m).error,true);assert.equal(core.summary(rows,calc,'2026-12').error,false);assert.equal(core.summary(rows,calc,'2026-12').expected,30);});
test('one-based display preserves existing stored references including absolute ranges',()=>{for(const formula of ['=C2*3','=SUM($C$2:D4)+100','=C3+C2','81930'])assert.equal(core.addresses(core.addresses(formula,-1),1),formula);assert.equal(core.addresses('=SUM($C$2:D4)',-1),'=SUM($C$1:D3)');const rows=[row(10),row(core.addresses('=C1*3',1))];assert.equal(core.calculate(rows).rows[1].estimate.value,30);assert.equal(core.addresses(core.copy(rows,1,'copy').estimate,-1),'=C2*3');assert.equal(core.addresses(core.remove(rows,0)[0].estimate,-1),'=#REF!*3');});
test('numeric deadline accepts eight digits, preserves partial/invalid input and checks leap years',()=>{assert.equal(core.normalizeDate('20260925'),'2026-09-25');assert.equal(core.normalizeDate('20270105'),'2027-01-05');assert.equal(core.normalizeDate('20240229'),'2024-02-29');for(const value of ['20260229','20261301','20260931','202609','2026-09-25','2026/9/25',''])assert.equal(core.normalizeDate(value),value);const rows=[row(81930,{date:core.normalizeDate('20260925')})];assert.equal(core.summary(rows,core.calculate(rows),'2026-09').remaining,81930);assert.equal(core.calculate([row(81930,{date:core.normalizeDate('20260230')})]).error,true);});
test('arithmetic precedence, parentheses, comma numbers and rounded won',()=>{const a=core.calculate([row('=81930+5000'),row('=(100+50)*2/3'),row('229,760'),row('=10/3')]);assert.deepEqual(Array.from(a.rows,r=>r.estimate.value),[86930,100,229760,3]);});
test('cell references and SUM support dependencies without counting total rows twice',()=>{const rows=[row(81930),row(229760),row('=C2+C3'),row('=SUM(C2:C4)',{kind:'total'})],calc=core.calculate(rows);assert.equal(calc.rows[3].estimate.value,623380);assert.equal(core.summary(rows,calc,'2026-09').estimate,623380);});
test('cycles, zero division, bad references and executable text fail closed',()=>{for(const [expr,error] of [['=C2','#CYCLE!'],['=1/0','#DIV/0!'],['=C99','#REF!'],['=A2','#VALUE!'],['=fetch("x")','#FORMULA!'],['=1e9','#FORMULA!']]){const a=core.calculate([row(expr)]);assert.equal(a.rows[0].estimate.error,error);assert.equal(a.error,true);}assert.equal(core.calculate([row('=C3'),row('=C2')]).error,true);});
test('deletion adjusts range and references; missing referenced cell becomes visible REF error',()=>{let rows=[row(10),row(20),row(30),row('=SUM(C2:C4)',{kind:'total'})];let next=core.remove(rows,1);assert.equal(next[2].estimate,'=SUM(C2:C3)');assert.equal(core.calculate(next).rows[2].estimate.value,40);next=core.remove([row(10),row('=C2')],0);assert.equal(next[0].estimate,'=#REF!');assert.equal(core.calculate(next).error,true);});
test('row copy shifts relative references and resets paid state',()=>{const rows=[row(10),row('=C2*3',{paid:true,actual:'30'})];const copy=core.copy(rows,1,'copy');assert.equal(copy.estimate,'=C3*3');assert.equal(copy.actual,'');assert.equal(copy.paid,false);assert.equal(core.copy([row('=$C$2')],0,'copy').estimate,'=$C$2');});
test('monthly totals use deadlines and actual payment, incomplete rows never report false zero',()=>{const rows=[row(81930),row(229760,{date:'2026-10-25',paid:true,actual:'220000'}),row('=SUM(C2:C3)',{kind:'total',date:''})],calc=core.calculate(rows);assert.equal(core.summary(rows,calc,'2026-09').remaining,81930);assert.equal(core.summary(rows,calc,'2026-10').expected,220000);assert.equal(core.calculate([row(1,{date:'2026-02-30'})]).error,true);assert.equal(core.calculate([row(1,{paid:true})]).error,true);assert.equal(core.valid({version:1,rows:rows}),true);assert.equal(core.valid({version:1,rows:[rows[0],rows[0]]}),false);});

test('recurring payments project into future months with month end clamp and independent overrides',()=>{
 const r=row(100,{date:'2026-01-31'});core.enableRepeat(r);const rows=[r];
 assert.equal(core.project(rows,'2026-02')[0].date,'2026-02-28');assert.equal(core.project(rows,'2028-02')[0].date,'2028-02-29');assert.equal(core.summary(rows,core.calculate(rows),'2025-12').expected,0);
 const feb=core.project(rows,'2026-02')[0];core.editMonth(r,'2026-02','estimate','250',feb);core.editMonth(r,'2026-02','actual','240',feb);core.editMonth(r,'2026-02','paid',true,feb);
 assert.equal(core.summary(rows,core.calculate(rows),'2026-02').expected,240);assert.equal(core.summary(rows,core.calculate(rows),'2026-03').expected,100);assert.equal(core.summary(rows,core.calculate(rows),'2026-01').expected,100);
 assert.equal(core.project(rows,'2026-03')[0].paid,false);assert.equal(core.monthDetails(rows,core.calculate(rows),'2026-02',[])[0].amount,240);
 assert.equal(core.valid({version:1,rows}),true);r.recurrence.end='2026-02';assert.equal(core.summary(rows,core.calculate(rows),'2026-03').expected,0);assert.equal(core.summary(rows,core.calculate(rows),'2026-02').expected,240);
});
test('recurring incomplete month affects only its month and formula edits survive structural deletion',()=>{
 const a=row(10),r=row(20);core.enableRepeat(r);let rows=[a,r];core.editMonth(r,'2026-10','estimate','=C2*3',core.project(rows,'2026-10')[1]);
 assert.equal(core.summary(rows,core.calculate(rows),'2026-10').expected,30);let next=core.remove(rows,0);assert.equal(next[0].recurrence.overrides['2026-10'].estimate,'=#REF!*3');assert.equal(core.summary(next,core.calculate(next),'2026-10').error,true);assert.equal(core.summary(next,core.calculate(next),'2026-11').expected,20);
 const clone=core.copy(core.project(rows,'2026-10'),1,'copy');assert.equal(clone.recurrence,undefined);assert.equal(clone.paid,false);
});
test('legacy import preserves versions, paid history, deduplication and deleted plan tombstones without mutating source',()=>{
 const plan={id:'old',plan:{name:'보험료',amount:100,day:31,frequency:'monthly',start:'2026-01',end:'',versions:[{from:'2026-03',name:'보험료',amount:200,day:10}],paid:{'2026-02':{amount:90,date:'2026-02-27'}}}};
 const source={version:1,rows:[row('=1+2')]},before=JSON.stringify([source,plan]);let sheet=core.importPlans(source,[plan]);assert.equal(JSON.stringify([source,plan]),before);assert.equal(sheet.rows.length,2);assert.equal(core.valid(sheet),true);
 const calc=core.calculate(sheet.rows);assert.equal(core.summary(sheet.rows,calc,'2026-02').expected,90);assert.equal(core.summary(sheet.rows,calc,'2026-04').expected,200);assert.equal(core.project(sheet.rows,'2026-03')[1].date,'2026-03-10');
 sheet=core.importPlans(JSON.parse(JSON.stringify(sheet)),[plan]);assert.equal(sheet.rows.length,2);sheet.rows=core.remove(sheet.rows,1);assert.equal(core.importPlans(sheet,[plan]).rows.length,1);
});
test('recurrence validation rejects malformed schedules and overrides',()=>{
 const r=row(100);core.enableRepeat(r);r.recurrence.day=32;assert.equal(core.valid({version:1,rows:[r]}),false);r.recurrence.day=25;r.recurrence.overrides['2026-13']={};assert.equal(core.valid({version:1,rows:[r]}),false);
});
