const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const code=fs.readFileSync('js/insuwork.js','utf8');
const owner='owner';
const item=(id,type='folder',parent=null,category='file')=>({id,item_type:type,parent_id:parent,owner_id:owner,title:id,legacy_payload:{workspace_category:category}});
function setup(user=owner){
 const writes=[],messages=[];const ctx={state:{data:{items:[item('a'),item('b','folder','a'),item('c','folder','b'),item('other'),item('memo','folder',null,'memo'),item('f','file'),{...item('foreign'),owner_id:'stranger'}]},favorites:[],assetView:'thumb'},authenticated:()=>!!user,currentUserId:()=>user,AZ_VIEWING_ROOM_OWNER_ID:owner,document:{addEventListener(){},getElementById:()=>null,querySelector:()=>null},window:{toast:t=>messages.push(t)},requestAnimationFrame:fn=>fn(),renderContent(){},saveError:e=>{throw e},dialog:html=>{ctx.dialogHtml=html},closeDialog(){},briefingPrompt:(...args)=>{ctx.promptArgs=args;return Promise.resolve('새 이름')},assetCategory:i=>i.legacy_payload.workspace_category,assetCategoryLabel:c=>c,workspaceItem:id=>ctx.state.data.items.find(i=>i.id===id),esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),isFavorited:()=>false,formatDate:()=>'',assetOpenAction:()=>"void(0)",assetDragAttributes:()=>'',syncPublicLibraryItem(){},updateOne:async(q,data)=>{writes.push({q,data});return {...ctx.workspaceItem(decodeURIComponent(q.match(/id=eq\.([^&]+)/)[1])),...data}},writeOne:async(t,data)=>{writes.push({t,data});return{id:'new-folder',...data}},upsertWorkspaceItem:r=>{const n=ctx.state.data.items.findIndex(i=>i.id===r.id);if(n<0)ctx.state.data.items.push(r);else ctx.state.data.items[n]=r}};
 vm.createContext(ctx);vm.runInContext(code.slice(code.indexOf('  // Owner-preview card actions.'),code.indexOf('  function fileExtension(item)')),ctx);
 return {ctx,writes,messages,select:id=>vm.runInContext('assetMenuTarget='+JSON.stringify(id),ctx)};
}
test('owner gate rejects ordinary/anonymous/foreign/deleted items',()=>{for(const u of ['ordinary',''])assert.equal(setup(u).ctx.actionableAsset('f'),null);const {ctx}=setup();assert.equal(ctx.actionableAsset('foreign'),null);ctx.workspaceItem('f').deleted_at='now';assert.equal(ctx.actionableAsset('f'),null)});
test('destinations reject self, descendants, cross-category and foreign folders',()=>{const {ctx}=setup();const a=ctx.workspaceItem('a');for(const id of ['a','b','c','memo','foreign','missing','f'])assert.equal(ctx.validAssetDestination(a,id),false,id);assert.equal(ctx.validAssetDestination(a,'other'),true);assert.equal(ctx.validAssetDestination(a,null),true);ctx.workspaceItem('other').parent_id='other';assert.equal(ctx.validAssetDestination(a,'other'),false)});
test('rename patches only title, keeps storage identity and visibility',async()=>{const {ctx,writes,select}=setup();Object.assign(ctx.workspaceItem('f'),{storage_path:'private/original.pdf',visibility:'private'});select('f');await ctx.assetMenuAction('rename');assert.equal(ctx.promptArgs[2],'f');assert.deepEqual(JSON.parse(JSON.stringify(writes[0].data)),{title:'새 이름'});assert.match(writes[0].q,/owner_id=eq.owner&deleted_at=is.null/);assert.equal(ctx.workspaceItem('f').storage_path,'private/original.pdf')});
test('move updates only parent and keeps descendants attached',async()=>{const {ctx,writes}=setup();ctx.assetMoveOpen('a');ctx.assetMoveEnter('other');await ctx.assetMoveConfirm();assert.deepEqual(JSON.parse(JSON.stringify(writes[0].data)),{parent_id:'other'});assert.equal(ctx.workspaceItem('b').parent_id,'a');assert.equal(ctx.workspaceItem('c').parent_id,'b')});
test('root move and duplicate submission',async()=>{const {ctx,writes}=setup();ctx.assetMoveOpen('b');ctx.assetMoveEnter('');const first=ctx.assetMoveConfirm();await ctx.assetMoveConfirm();await first;assert.equal(writes.length,1);assert.equal(writes[0].data.parent_id,null)});
test('create folder uses destination and original category',async()=>{const {ctx,writes}=setup();ctx.assetMoveOpen('f');ctx.assetMoveEnter('other');await ctx.assetMoveNewFolder();assert.equal(writes[0].data.parent_id,'other');assert.equal(writes[0].data.visibility,'private');assert.equal(writes[0].data.legacy_payload.workspace_category,'file');await ctx.assetMoveConfirm();assert.equal(writes[1].data.parent_id,'new-folder')});
test('folder cards have independent more button and escaped titles without folder image',()=>{const {ctx}=setup();const card=ctx.assetActionCard({title:'<img onerror=x>',folder:true,raw:{id:'a'}},'unused');assert.match(card,/<article/);assert.match(card,/&lt;img onerror=x&gt;/);assert.doesNotMatch(card,/iw-folder-icon|<img/);assert.equal((card.match(/<button /g)||[]).length,2);assert.match(card,/event.stopPropagation/)});
test('navigation hides forbidden descendants and same-folder move is disabled',()=>{const {ctx}=setup();ctx.assetMoveOpen('a');assert.doesNotMatch(ctx.dialogHtml,/data-folder="a"/);assert.doesNotMatch(ctx.dialogHtml,/data-folder="foreign"/);assert.match(ctx.dialogHtml,/ disabled/)});
