const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const key='__coverage_workspace__';
function setup(){const saved=[],loaded=[];let failSave=false,failExtract=false;const api={getCoverageCustomerInfo:id=>({id,name:'고객'+id,birthDate:'1980-01-01'}),getCoverageBaseTemplate:()=>({rows:[{id:'r',section:'암',name:'암 진단비',total:'999만',values:{p:'999만'}}],products:[{id:'p'}]}),saveCoverageWorkspaceDraft:async r=>{if(failSave)throw Error('저장 실패');saved.push(JSON.parse(JSON.stringify(r)));return r;},loadCoveragePdfFile:async(id,customerId)=>{loaded.push([id,customerId]);return {name:id+'.pdf',buffer:new Uint8Array([1])}},extractCoverageFile:async file=>{if(failExtract)throw Error('분석 실패');return {products:[{company:'보험사',product:'상품'}],rows:[{section:'암',name:'암 진단비',values:['100만'],total:'100만'}]};},rerenderCoverageWorkspace(){}};const c={File,crypto:webcrypto,queueMicrotask(){},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return []}},fetch:async()=>({ok:true,json:async()=>({entries:[]})}),window:{OSInsuwork:api}};vm.createContext(c);vm.runInContext(fs.readFileSync('js/insuwork-coverage.js','utf8').replace('window.OSInsuworkCoverage = exposed;','window.OSInsuworkCoverage = exposed;window.getDraft=draft;'),c);return {ui:c.window.OSInsuworkCoverage,draft:()=>c.window.getDraft(key),saved,loaded,failSave:()=>failSave=true,failExtract:()=>failExtract=true};}
test('switch preserves current edits before opening saved customer; returning resumes cached draft',async()=>{const s=setup();s.ui.reset(key,{customerInfo:{id:'a',name:'고객a'},rows:[{id:'x',name:'수정 담보',values:{},total:'500만'}],products:[]});await s.ui.openCustomerWorkspace('b',{customerInfo:{id:'b',name:'고객b'},rows:[],products:[]});assert.equal(s.saved[0].rows[0].total,'500만');assert.equal(s.draft().customerInfo.id,'b');await s.ui.openCustomerWorkspace('a',null);assert.equal(s.draft().rows[0].total,'500만');});
test('save failure prevents customer switch',async()=>{const s=setup();s.ui.reset(key,{customerInfo:{id:'a'},rows:[],products:[]});s.failSave();await assert.rejects(s.ui.openCustomerWorkspace('b',null),/저장 실패/);assert.equal(s.draft().customerInfo.id,'a');});
test('new customer starts clean template and gets explicit customer save label',async()=>{const s=setup();await s.ui.openCustomerWorkspace('b',null);assert.equal(s.draft().products.length,0);assert.equal(s.draft().rows[0].total,'');assert.deepEqual(Object.keys(s.draft().rows[0].values),[]);assert.match(s.ui.workspaceHtml(),/고객b 고객에게 저장/);assert.match(s.ui.workspaceHtml(),/자료 추가 분석/);});
test('multiple existing PDFs use modern extraction, preserve old references, deduplicate contract and save no uploads',async()=>{const s=setup();await s.ui.openCustomerWorkspace('b',null);s.draft().source={files:[{id:'old',name:'old.pdf'}]};await s.ui.importCustomerPdfs('b',['one','two']);assert.equal(s.loaded.length,2);assert.ok(s.loaded.every(x=>x[1]==='b'));assert.equal(s.draft().products.length,1);assert.equal(s.draft().source.files.length,3);assert.equal(s.draft().rows[0].total,'100만');assert.equal(s.saved.length,1);});
test('wrong customer import rejects before accessing file',async()=>{const s=setup();await s.ui.openCustomerWorkspace('b',null);await assert.rejects(s.ui.importCustomerPdfs('a',['one']),/고객이 다릅니다/);assert.equal(s.loaded.length,0);});
test('attachment resolver excludes another owner, customer and deleted file',()=>{const app=fs.readFileSync('js/insuwork.js','utf8');const base={owner_id:'owner',storage_path:'path',extension:'pdf'};const c={state:{data:{consultations:[],items:[{id:'root',owner_id:'owner',legacy_payload:{customer_id:'a',attachment_root:true}},...['yes','foreign','deleted','other'].map(id=>({...base,id,parent_id:id==='other'?'other-root':'root',owner_id:id==='foreign'?'other':'owner',deleted_at:id==='deleted'?'now':null}))]}},currentUserId:()=> 'owner'};vm.createContext(c);vm.runInContext(app.slice(app.indexOf('  function customerCoveragePdfFiles('),app.indexOf('  function openCustomerCoverage(')),c);assert.equal(c.customerCoveragePdfFiles('a').map(f=>f.id).join(','),'yes');});
