const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const encrypted=Uint8Array.from([0xd0,0xcf,0x11,0xe0,0,0,0,0,0]).buffer;
function setup(answers,fail=false){const prompts=[],passwords=[];const context={window:{Buffer,prompt:message=>{prompts.push(message);return answers.shift();},OSOfficeCrypto:{decrypt:async(data,options)=>{passwords.push(options.password);if(fail)throw Error('incorrect password');return [1,2,3];}}},document:{addEventListener(){}}};vm.createContext(context);vm.runInContext(fs.readFileSync('js/insuwork-coverage.js','utf8').replace('window.OSInsuworkCoverage = exposed;','window.helpers={decryptWorkbook,applyWorkbookPasswordBirth};window.OSInsuworkCoverage = exposed;'),context);return {h:context.window.helpers,prompts,passwords};}
test('BankSalad uses per-file birth date; missing century requires explicit year',async()=>{const {h,prompts,passwords}=setup(['900315','1990']);const hint={};await h.decryptWorkbook(encrypted,'고객_뱅크샐러드.xlsx',hint);assert.match(prompts[0],/고객 생년월일 6자리/);const result=h.applyWorkbookPasswordBirth({customerInfo:{}},hint);assert.equal(result.customerInfo.birthDate,'1990-03-15');assert.deepEqual(passwords,['900315']);});
test('Bomapp employee number never becomes customer birth date',async()=>{const {h,prompts}=setup(['900315']);const hint={};await h.decryptWorkbook(encrypted,'보맵.xlsx',hint);assert.match(prompts[0],/본인의 사번/);assert.equal(hint.birthSix,undefined);assert.equal(h.applyWorkbookPasswordBirth({customerInfo:{}},hint).customerInfo.birthDate,undefined);assert.equal(prompts.length,1);});
test('unknown provider explains both rules but does not infer birth date',async()=>{const {h,prompts}=setup(['123456']);const hint={};await h.decryptWorkbook(encrypted,'export.xlsx',hint);assert.match(prompts[0],/뱅크샐러드.*보맵/);assert.deepEqual(hint,{});});
test('unencrypted file never asks; failed decrypt never yields identity',async()=>{const {h,prompts}=setup(['900315'],true);await h.decryptWorkbook(new Uint8Array([1,2]).buffer,'뱅크샐러드.xlsx',{});assert.equal(prompts.length,0);const hint={};await assert.rejects(h.decryptWorkbook(encrypted,'뱅크샐러드.xlsx',hint),/비밀번호가 맞지/);assert.deepEqual(hint,{});});
test('document date is retained and mismatching date is rejected',()=>{const {h,prompts}=setup([]);const record={customerInfo:{birthDate:'1990-03-15'}};assert.equal(h.applyWorkbookPasswordBirth(record,{birthSix:'900315'}),record);assert.equal(prompts.length,0);assert.throws(()=>h.applyWorkbookPasswordBirth(record,{birthSix:'000315'}),/생년월일이 다릅니다/);});
test('cancelled century leaves birth empty; invalid and mismatching years rejected',()=>{let {h}=setup([null]);assert.equal(h.applyWorkbookPasswordBirth({customerInfo:{}},{birthSix:'000315'}).customerInfo.birthDate,undefined);({h}=setup(['1991']));assert.throws(()=>h.applyWorkbookPasswordBirth({customerInfo:{}},{birthSix:'900315'}),/출생연도/);});
