const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const owner='98c5f4f9-10c1-4ee1-a656-5c2ca63239fd';
const source=fs.readFileSync('insuwork/ledger.js','utf8');
function boot(id,token){const calls=[];const context={window:{AppState:{userId:id},db:{getToken:()=>token,fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>[]};}}},localStorage:{getItem:()=>null},sessionStorage:{getItem:()=>null},document:{addEventListener:()=>{}},console};vm.createContext(context);vm.runInContext(source.replace('window.OSInsuworkLedger={','window.testLedger={valid,total,request,scope};window.OSInsuworkLedger={'),context);return {...context,calls};}
test('only exact owner with session can open; anonymous and other accounts deny without requests',async()=>{for(const [id,token] of [[null,null],[owner,null],['other','session']]){const c=boot(id,token);assert.equal(c.window._canSeeInsuworkLedger(),false);assert.match(c.window.OSInsuworkLedger.html(),/전용/);await assert.rejects(c.window.testLedger.request(''));assert.equal(c.calls.length,0);}assert.equal(boot(owner,'session').window._canSeeInsuworkLedger(),true);});
test('reads scoped private ledger only; no token or personal data in URL',async()=>{const c=boot(owner,'session');await c.window.testLedger.request('?'+c.window.testLedger.scope());assert.match(c.calls[0].url,/owner_id=eq\.98c5/);assert.match(c.calls[0].url,/visibility=eq.private/);assert.match(c.calls[0].url,/setting_key=eq.personal_ledger_v1/);assert.match(c.calls[0].url,/deleted_at=is.null/);});
test('reject invalid calendar dates, decimals, unsafe amounts and unknown types',()=>{const {valid}=boot(owner,'session').window.testLedger;const entry={date:'2026-08-31',type:'expense',amount:12000,category:'식비',memo:'점심'};assert.equal(valid(entry),true);for(const change of [{date:'2026-02-30'},{amount:1.5},{amount:-1},{amount:Infinity},{amount:1e16},{type:'transfer'},{category:'<script>'},{memo:'x'.repeat(121)}])assert.equal(valid({...entry,...change}),false);});
test('income minus spending is net flow, zero and large integer totals stay exact',()=>{const {total}=boot(owner,'session').window.testLedger;assert.equal(total([]).income,0);const sums=total([{legacy_payload:{entry:{type:'income',amount:4000000}}},{legacy_payload:{entry:{type:'expense',amount:15000}}},{legacy_payload:{entry:{type:'expense',amount:85000}}}]);assert.equal(sums.income-sums.expense,3900000);});
