Add-Type -AssemblyName System.Drawing
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$W=1080; $H=1350
$navy=[Drawing.ColorTranslator]::FromHtml('#0D326F'); $ink=[Drawing.ColorTranslator]::FromHtml('#17233D'); $muted=[Drawing.ColorTranslator]::FromHtml('#596173'); $paper=[Drawing.ColorTranslator]::FromHtml('#FBFAF7'); $gold=[Drawing.ColorTranslator]::FromHtml('#9A7423'); $teal=[Drawing.ColorTranslator]::FromHtml('#167C76'); $line=[Drawing.ColorTranslator]::FromHtml('#E3DDCF')
function Font($size,$bold=$false){New-Object Drawing.Font('Malgun Gothic',$size,($(if($bold){[Drawing.FontStyle]::Bold}else{[Drawing.FontStyle]::Regular})),[Drawing.GraphicsUnit]::Pixel)}
function RoundRect($g,$brush,$pen,$x,$y,$w,$h,$r){$p=New-Object Drawing.Drawing2D.GraphicsPath;$p.AddArc($x,$y,$r,$r,180,90);$p.AddArc($x+$w-$r,$y,$r,$r,270,90);$p.AddArc($x+$w-$r,$y+$h-$r,$r,$r,0,90);$p.AddArc($x,$y+$h-$r,$r,$r,90,90);$p.CloseFigure();if($brush){$g.FillPath($brush,$p)};if($pen){$g.DrawPath($pen,$p)};$p.Dispose()}
function Text($g,$s,$font,$color,$x,$y,$w,$h){$b=New-Object Drawing.SolidBrush($color);$f=New-Object Drawing.StringFormat;$f.Trimming=[Drawing.StringTrimming]::Word;$g.DrawString($s,$font,$b,[Drawing.RectangleF]::new($x,$y,$w,$h),$f);$b.Dispose();$f.Dispose()}
function Base($n,$label){$bmp=New-Object Drawing.Bitmap($W,$H);$g=[Drawing.Graphics]::FromImage($bmp);$g.SmoothingMode='HighQuality';$g.TextRenderingHint='ClearTypeGridFit';$g.Clear($paper);Text $g '보험워크 · 실손 재가입 안내' (Font 24 $true) $gold 72 60 700 45;RoundRect $g (New-Object Drawing.SolidBrush($navy)) $null 944 52 64 64 22;Text $g $n (Font 28 $true) ([Drawing.Color]::White) 960 64 50 45;@($bmp,$g)}
function Panel($g,$x,$y,$w,$h){RoundRect $g (New-Object Drawing.SolidBrush([Drawing.Color]::White)) (New-Object Drawing.Pen($line,2)) $x $y $w $h 26}
function Bottom($g,$s){RoundRect $g (New-Object Drawing.SolidBrush($navy)) $null 72 1180 936 110 24;Text $g $s (Font 30 $true) ([Drawing.Color]::White) 104 1204 872 68}

# 1
$a=Base '1' ''; $bmp=$a[0];$g=$a[1];Text $g '먼저 내 계약부터 확인하세요' (Font 30 $true) $teal 72 170 760 48;Text $g "나는 실손보험`n재가입 대상일까요?" (Font 65 $true) $ink 72 220 850 180;Text $g "가입 시기만으로 단정하지 마세요.`n보험증권과 약관을 확인해야 합니다." (Font 34) $muted 72 420 850 115;Panel $g 72 570 650 430;Text $g '꼭 확인할 4가지' (Font 38 $true) $ink 112 610 500 58;Text $g "✓ 최초 가입일`n✓ 현재 상품명`n✓ 재가입 조항`n✓ 재가입 예정일" (Font 34 $true) $teal 112 690 400 225;Text $g "2013년 3월 이전 계약 중에는`n재가입 조건이 없는 계약도 있습니다." (Font 32) $ink 112 910 520 100;$img=[Drawing.Image]::FromFile((Join-Path $root 'renewal-advisor.png'));$g.DrawImage($img,590,680,540,440);$img.Dispose();Bottom $g '세대보다 내 약관의 재가입 조항을 먼저 확인하세요.';$bmp.Save((Join-Path $root 'customer-card-01.png'),[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose()

# 2
$a=Base '2' ''; $bmp=$a[0];$g=$a[1];Text $g '보험사 안내를 받았다면' (Font 30 $true) $teal 72 170 700 48;Text $g "이 순서대로`n확인하세요" (Font 65 $true) $ink 72 220 850 180;Panel $g 72 440 936 690;$steps=@(@('1','안내문 도착 여부 확인','문자·우편·앱 알림과 연락처를 확인하세요.'),@('2','바뀌는 조건 비교','보장·자기부담금·보험료를 확인하세요.'),@('3','기한 안에 의사 표시','안내문에 적힌 방법으로 응답하세요.'),@('4','완료 여부 다시 확인','처리 결과와 새 보험증권을 확인하세요.'));$y=485;foreach($s in $steps){RoundRect $g (New-Object Drawing.SolidBrush($navy)) $null 112 $y 68 68 20;Text $g $s[0] (Font 30 $true) ([Drawing.Color]::White) 132 ($y+10) 45 45;Text $g $s[1] (Font 34 $true) $ink 215 ($y-5) 720 50;Text $g $s[2] (Font 34) $muted 215 ($y+48) 730 58;$y+=158};Bottom $g '보험금 청구 중이어도 재가입 완료 여부는 따로 확인하세요.';$bmp.Save((Join-Path $root 'customer-card-02.png'),[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose()

# 3
$a=Base '3' ''; $bmp=$a[0];$g=$a[1];Text $g '응답을 놓쳤거나 연락을 못 받았다면' (Font 30 $true) $teal 72 170 860 48;Text $g "자동연장일까요?`n보장이 끝날까요?" (Font 62 $true) $ink 72 220 900 180;Text $g "정답은 하나가 아닙니다.`n상품과 약관에 따라 달라질 수 있습니다." (Font 33) $muted 72 415 900 105;$items=@(@('자동연장 여부','모든 계약의 기준이 같지는 않습니다.'),@('보장 종료 여부','세대명만 보고 단정하지 마세요.'),@('철회·환급 가능 여부','기간과 환급 범위를 확인하세요.'),@('연락처 변경','보험사에 최신 정보를 등록하세요.'));$y=545;foreach($it in $items){Panel $g 72 $y 936 130;Text $g $it[0] (Font 32 $true) $navy 110 ($y+14) 800 45;Text $g $it[1] (Font 34) $muted 110 ($y+58) 830 50;$y+=145};Bottom $g '보험증권과 안내문을 준비해 내 계약 기준으로 확인하세요.';$bmp.Save((Join-Path $root 'customer-card-03.png'),[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose()

# 4 — 스마트폰용 큰 글씨 세로 체크리스트
$a=Base '4' ''; $bmp=$a[0];$g=$a[1];Text $g '고객에게 보내기 전 확인' (Font 30 $true) $teal 72 150 800 48;Text $g "실손 재가입`n체크리스트" (Font 58 $true) $ink 72 205 850 145;Panel $g 72 375 936 700;$rows=@(@('1  계약 정보','보험사 · 상품명 · 최초 가입일'),@('2  재가입 조항','조항 유무 · 주기 · 예정일'),@('3  변경 조건','보장 · 자기부담금 · 보험료'),@('4  미응답 처리','자동연장 또는 종료 여부'),@('5  철회·환급','가능 기간과 환급 방식'),@('6  안내 기록','문자 · 통화 · 상담 일시'));$y=405;foreach($r in $rows){Text $g $r[0] (Font 31 $true) $navy 110 $y 800 42;Text $g $r[1] (Font 32) $muted 110 ($y+46) 820 42;$y+=108};Text $g '기준일 2026-08-27 · 계약 약관과 보험사 안내문 우선' (Font 22 $true) $gold 92 1100 900 38;Bottom $g '가입 시기와 상품 약관에 따라 재가입 기준이 다릅니다.';$bmp.Save((Join-Path $root 'advisor-checklist.png'),[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose()
