(function () {
  'use strict';
  var OWNER='98c5f4f9-10c1-4ee1-a656-5c2ca63239fd', KEY='personal_ledger_v1';
  var month=today().slice(0,7), rows=[], root=null, busy=false, generation=0;
  var categories=['식비','생활','교통','주거·통신','건강','여가','급여','기타'];
  function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function canSee(){try{var u=window.AppState, s=JSON.parse(localStorage.getItem('os_user')||sessionStorage.getItem('os_user')||'{}');return String(u&&u.userId||s.id||'')===OWNER&&!!(window.db&&window.db.fetch&&window.db.getToken&&window.db.getToken());}catch(_){return false;}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function valid(v){return v&&/^\d{4}-\d{2}-\d{2}$/.test(v.date)&&!isNaN(Date.parse(v.date))&&new Date(v.date).toISOString().slice(0,10)===v.date&&['income','expense'].includes(v.type)&&Number.isSafeInteger(v.amount)&&v.amount>0&&v.amount<=999999999999&&categories.includes(v.category)&&typeof v.memo==='string'&&v.memo.length<=120;}
  function total(list){return list.reduce(function(t,r){var v=r.legacy_payload.entry;t[v.type]+=v.amount;return t;},{income:0,expense:0});}
  function money(n){return n.toLocaleString('ko-KR')+'원';}
  function scope(){return 'owner_id=eq.'+OWNER+'&item_type=eq.memo&visibility=eq.private&legacy_payload->>setting_key=eq.'+KEY+'&deleted_at=is.null';}
  async function request(query,method,body){if(!canSee())throw Error('임태성 전용 화면입니다.');var options={method:method||'GET',headers:{'Content-Type':'application/json',Prefer:'return=representation'}};if(body)options.body=JSON.stringify(body);var r=await window.db.fetch('/rest/v1/insuwork_items'+query,options);if(!r.ok)throw Error('저장소에 연결하지 못했습니다. 다시 시도해 주세요. ('+r.status+')');var result=await r.json();if(!canSee())throw Error('로그인을 다시 확인해 주세요.');return result;}
  function html(){return canSee()?'<section class="iwl-page" data-iwl-page><p role="status">가계부를 불러오는 중입니다.</p></section>':'<p>임태성 전용 화면입니다.</p>';}
  function message(text){var el=root&&root.querySelector('[data-iwl-status]');if(el)el.textContent=text;}
  function paint(){if(!root||!root.isConnected)return;if(!canSee()){root.innerHTML='<p>임태성 전용 화면입니다.</p>';rows=[];return;}var list=rows.filter(function(r){return r.legacy_payload.entry.date.slice(0,7)===month;}).sort(function(a,b){return b.legacy_payload.entry.date.localeCompare(a.legacy_payload.entry.date)||b.id.localeCompare(a.id);}), sums=total(list);
    root.innerHTML='<header class="iwl-head"><div><h2>가계부</h2><p>임태성 전용 · 내 계정에 비공개로 저장됩니다.</p></div><label>조회 월 <input type="month" data-iwl-month value="'+month+'" required></label></header>'+
      '<div class="iwl-totals"><article><span>수입</span><strong>'+money(sums.income)+'</strong></article><article><span>지출</span><strong>'+money(sums.expense)+'</strong></article><article><span>수입 − 지출</span><strong>'+money(sums.income-sums.expense)+'</strong></article></div>'+
      '<form class="iwl-form"><h3 data-iwl-form-title>내역 추가</h3><input type="hidden" name="id"><label>날짜<input name="date" type="date" value="'+today()+'" required></label><label>구분<select name="type"><option value="expense">지출</option><option value="income">수입</option></select></label><label>금액 (원)<input name="amount" type="number" inputmode="numeric" min="1" max="999999999999" step="1" required placeholder="0"></label><label>분류<select name="category">'+categories.map(function(c){return '<option>'+c+'</option>';}).join('')+'</select></label><label class="iwl-memo">내용<input name="memo" maxlength="120" placeholder="예: 점심 식사"></label><div class="iwl-actions"><button type="submit">저장</button><button type="button" data-iwl-cancel hidden>수정 취소</button></div></form>'+
      '<p data-iwl-status role="status" aria-live="polite"></p><div class="iwl-list-head"><h3>'+esc(month)+' 내역 · '+list.length+'건</h3><button type="button" data-iwl-refresh>새로고침</button></div><div class="iwl-list">'+(list.map(function(r){var v=r.legacy_payload.entry;return '<article class="iwl-row"><div><small>'+esc(v.date)+' · '+esc(v.category)+'</small><strong>'+esc(v.memo||v.category)+'</strong></div><b>'+ (v.type==='income'?'+':'−')+money(v.amount)+'</b><div class="iwl-row-actions"><button type="button" data-iwl-edit="'+esc(r.id)+'">수정</button><button type="button" data-iwl-delete="'+esc(r.id)+'">삭제</button></div></article>';}).join('')||'<p class="iwl-empty">아직 내역이 없습니다. 첫 수입이나 지출을 기록해 보세요.</p>')+'</div>';
    root.querySelector('[data-iwl-month]').onchange=function(e){if(busy)return;if(/^\d{4}-\d{2}$/.test(e.target.value)){month=e.target.value;paint();}};
    root.querySelector('form').onsubmit=save;
    root.querySelector('[data-iwl-cancel]').onclick=paint;
    root.querySelector('[data-iwl-refresh]').onclick=load;
    root.querySelectorAll('[data-iwl-edit]').forEach(function(b){b.onclick=function(){if(busy||!canSee())return;var r=rows.find(function(r){return r.id===b.dataset.iwlEdit;}),v=r.legacy_payload.entry,f=root.querySelector('form');f.elements.id.value=r.id;['date','type','amount','category','memo'].forEach(function(k){f.elements[k].value=v[k];});root.querySelector('[data-iwl-form-title]').textContent='내역 수정';root.querySelector('[data-iwl-cancel]').hidden=false;f.elements.amount.focus();};});
    root.querySelectorAll('[data-iwl-delete]').forEach(function(b){b.onclick=function(){remove(b.dataset.iwlDelete);};});
  }
  function lock(value){busy=value;if(root)root.querySelectorAll('button,input,select').forEach(function(e){e.disabled=value;});}
  async function load(){if(busy||!root||!canSee())return;var ticket=++generation;lock(true);message('불러오는 중…');try{var all=[],offset=0;while(true){var part=await request('?'+scope()+'&select=id,legacy_payload&order=id&limit=500&offset='+offset);if(!Array.isArray(part))throw Error('자료 형식을 확인하지 못했습니다.');all=all.concat(part);if(part.length<500)break;offset+=500;}if(ticket!==generation)return;if(all.some(function(r){return !r.id||!valid(r.legacy_payload&&r.legacy_payload.entry);}))throw Error('확인할 수 없는 내역이 있습니다. 합계를 표시하지 않습니다.');rows=all;busy=false;paint();}catch(e){if(root&&root.isConnected){root.innerHTML='<p role="alert">'+esc(e.message)+'</p><button type="button" data-iwl-retry>다시 시도</button>';root.querySelector('button').onclick=load;}}finally{lock(false);}}
  async function save(e){e.preventDefault();if(busy||!canSee())return;var f=e.target,id=f.elements.id.value,v={date:f.elements.date.value,type:f.elements.type.value,amount:Number(f.elements.amount.value),category:f.elements.category.value,memo:f.elements.memo.value.trim()};if(!valid(v)){message('날짜와 금액을 확인해 주세요. 금액은 1원 이상의 정수로 입력합니다.');return;}if(id&&!rows.some(function(r){return r.id===id;}))return;lock(true);message('저장 중…');try{var body={owner_id:OWNER,item_type:'memo',title:'가계부',body:'',visibility:'private',legacy_payload:{workspace_category:'settings',setting_key:KEY,entry:v}};if(!id){f.dataset.requestId=f.dataset.requestId||crypto.randomUUID();body.id=f.dataset.requestId;}var saved=await request(id?'?'+scope()+'&id=eq.'+encodeURIComponent(id):'',id?'PATCH':'POST',body);if(!Array.isArray(saved)||saved.length!==1)throw Error('저장 결과를 확인하지 못했습니다. 새로고침 후 확인해 주세요.');rows=rows.filter(function(r){return r.id!==saved[0].id;});rows.push(saved[0]);month=v.date.slice(0,7);paint();message('저장했습니다.');}catch(error){message(error.message);}finally{lock(false);}}
  async function remove(id){if(busy||!canSee()||!rows.some(function(r){return r.id===id;}))return;var ok=window.InsuranceBriefingNotice&&window.InsuranceBriefingNotice.confirm?await window.InsuranceBriefingNotice.confirm({title:'내역 삭제',message:'이 내역을 삭제할까요?',confirmLabel:'삭제'}):window.confirm('이 내역을 삭제할까요?');if(!ok||busy||!canSee())return;lock(true);try{var result=await request('?'+scope()+'&id=eq.'+encodeURIComponent(id),'PATCH',{deleted_at:new Date().toISOString()});if(!Array.isArray(result)||result.length!==1)throw Error('삭제 결과를 확인하지 못했습니다.');rows=rows.filter(function(r){return r.id!==id;});paint();message('삭제했습니다.');}catch(e){message(e.message);}finally{lock(false);}}
  function mount(){var next=document.querySelector('[data-iwl-page]');if(!next||next===root)return;root=next;rows=[];busy=false;load();}
  window._canSeeInsuworkLedger=canSee;
  window.OSInsuworkLedger={html:html,mount:mount};
  document.addEventListener('appstate:ready',function(){if(!canSee()){generation++;rows=[];if(root)root.innerHTML='';}});
})();
