(function () {
  'use strict';
  var core=window.OSLedgerSheetCore,root=null,options=null,draft=null,base='',baseRevision=null,dirty=false,saving=false,month=localMonth();
  var fields=['name','date','estimate','actual','paid','memo'];
  function localMonth(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
  function nextMonth(m){var d=new Date(Number(m.slice(0,4)),Number(m.slice(5))-1+1,1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function allowed(){return !!(window._canSeeInsuworkLedger&&window._canSeeInsuworkLedger());}
  function empty(kind){return {id:crypto.randomUUID(),kind:kind||'expense',name:'',date:'',estimate:'',actual:'',paid:false,memo:''};}
  function money(n){return n.toLocaleString('ko-KR')+'원';}
  function note(s){var n=root&&root.querySelector('[data-iws-status]');if(n)n.textContent=s;}
  function combined(calc,m){var t=core.summary(draft.rows,calc,m),old=options.legacy(m);old.forEach(function(p){t.estimate+=p.estimate;if(p.paid)t.paid+=p.paid.amount;else t.remaining+=p.estimate;});t.expected=t.paid+t.remaining;return t;}
  function summaryHtml(calc){var now=localMonth(),selected=combined(calc,month);return '<div class="iwl-months">'+[now,nextMonth(now)].map(function(m,i){var t=combined(calc,m);return '<button type="button" data-iws-month="'+m+'" aria-pressed="'+(m===month)+'"><span>'+(i?'다음 달':'이번 달')+' · '+m+'</span><strong>'+(t.error?'입력·수식 확인':money(t.expected))+'</strong><small>'+(t.error?'표의 오류를 수정하면 합계가 표시됩니다.':'남은 예정 '+money(t.remaining)+' · 납부 '+money(t.paid))+'</small></button>';}).join('')+'</div><div class="iwl-totals iws-totals">'+[['예상 총지출',selected.expected],['납부 완료',selected.paid],['앞으로 남은 금액',selected.remaining]].map(function(x){return '<article><span>'+month+' '+x[0]+'</span><strong>'+(selected.error?'확인 필요':money(x[1]))+'</strong></article>';}).join('')+'</div>';}
  function cell(r,i,key){var addr=String.fromCharCode(65+fields.indexOf(key))+(i+2),disabled=r.kind==='total'&&(key==='date'||key==='paid'),type=key==='paid'?'checkbox':'text';var input='<input data-iws-row="'+i+'" data-iws-field="'+key+'" aria-label="'+addr+' '+({name:'항목',date:'납입기한',estimate:'예정 금액',actual:'실제 납부액',paid:'납부 완료',memo:'메모'}[key])+'" type="'+type+'" '+(key==='paid'?(r.paid?'checked':''):'value="'+esc(r[key])+'" maxlength="'+(key==='memo'?300:key==='date'?10:200)+'"'+(key==='date'?' inputmode="numeric" placeholder="YYYY-MM-DD" title="숫자 8자리 입력: 20260925 → 2026-09-25"':''))+(disabled?' disabled':'')+' autocomplete="off">';if(key==='date'){var iso=/^\d{4}-\d{2}-\d{2}$/.test(r.date)?r.date:'';input='<span class="iws-date-control">'+input+'<label class="iws-date-picker"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16"/></svg><input type="date" data-iws-picker="'+i+'" aria-label="'+addr+' 달력으로 납입기한 선택" title="달력에서 날짜 선택" value="'+esc(iso)+'"'+(disabled?' disabled':'')+'></label></span>';}return '<td>'+input+(['estimate','actual'].includes(key)?'<output data-iws-result="'+i+'-'+key+'"></output>':'')+'</td>';}
  function render(){if(!root||!root.isConnected||!allowed())return;var calc=core.calculate(draft.rows);root.innerHTML='<header class="iwl-head"><div><h2>가계부 · 지출표</h2><p>임태성 전용 · 셀을 수정한 뒤 표 저장을 눌러 주세요.</p></div><label>요약 조회 월<input data-iws-select-month type="month" value="'+month+'"></label></header><div data-iws-summary>'+summaryHtml(calc)+'</div><p class="iwl-explain">납입기한 기준으로 표의 지출 행과 기존 반복 예정 지출을 합산합니다. 합계용 행과 일반 수입·지출 기록은 중복 집계하지 않습니다. 변경 중에는 저장 전 예상값입니다.</p>'+
      '<div class="iws-toolbar"><button type="button" data-iws-add>행 추가</button><button type="button" data-iws-total>합계 행 추가</button><button type="button" data-iws-save>표 저장</button><button type="button" data-iws-reload>저장본 다시 불러오기</button><strong data-iws-dirty></strong></div><p class="iws-help">B열 납입기한: 20260925 → 2026-09-25 또는 달력 선택 · C·D열: 숫자 또는 =81930+5000, =C2*3, =SUM(C2:C6) · 사칙연산과 괄호 지원 · 원 단위 반올림 · Enter 다음 행 / Tab 다음 칸 · 휴대폰에서는 표를 좌우로 밀어 편집합니다.</p>'+
      '<div class="iws-scroll" tabindex="0" aria-label="지출표 가로 스크롤"><table class="iws-table"><thead><tr><th scope="col">행</th><th scope="col">A · 항목</th><th scope="col">B · 납입기한</th><th scope="col">C · 예정 금액</th><th scope="col">D · 실제 납부액</th><th scope="col">E · 납부 완료</th><th scope="col">F · 메모</th><th scope="col">행 관리</th></tr></thead><tbody>'+draft.rows.map(function(r,i){return '<tr class="'+(r.kind==='total'?'iws-total-row':'')+'"><th scope="row">'+(i+2)+(r.kind==='total'?'<small>합계용</small>':'')+'</th>'+fields.map(function(k){return cell(r,i,k);}).join('')+'<td><button type="button" data-iws-copy="'+i+'" aria-label="'+(i+2)+'행 복사">복사</button><button type="button" data-iws-delete="'+i+'" aria-label="'+(i+2)+'행 삭제">삭제</button><small data-iws-row-status="'+i+'"></small></td></tr>';}).join('')+'</tbody><tfoot><tr><th colspan="3">지출 행 자동합계</th><td data-iws-sum-estimate></td><td data-iws-sum-actual></td><td colspan="3">합계용 행 제외</td></tr></tfoot></table></div><p data-iws-status role="status" aria-live="polite"></p>';
    root.oninput=onInput;root.onchange=function(e){if(e.target.matches('[data-iws-select-month]')){if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)){month=e.target.value;refresh();}}else if(e.target.type==='checkbox'||e.target.hasAttribute('data-iws-picker'))onInput(e);};root.onclick=onClick;root.onkeydown=onKey;refresh();
  }
  function refresh(){if(!root||!allowed())return;var calc=core.calculate(draft.rows);root.querySelector('[data-iws-summary]').innerHTML=summaryHtml(calc);var totals={estimate:0,actual:0};draft.rows.forEach(function(r,i){var v=calc.rows[i];['estimate','actual'].forEach(function(k){var el=root.querySelector('[data-iws-result="'+i+'-'+k+'"]');el.textContent=v[k].error||money(v[k].value);el.classList.toggle('iws-error',!!v[k].error);if(r.kind!=='total'&&!v.error&&!v.empty)totals[k]+=v[k].value;});var status=root.querySelector('[data-iws-row-status="'+i+'"]');status.textContent=v.error||(r.kind==='total'?'합계 집계 제외':v.empty?'':r.paid?'납부 완료':r.date<new Date().toLocaleDateString('en-CA')?'기한 지남 · 미납':'납부 예정');status.classList.toggle('iws-error',!!v.error);});root.querySelector('[data-iws-sum-estimate]').textContent=calc.error?'확인 필요':money(totals.estimate);root.querySelector('[data-iws-sum-actual]').textContent=calc.error?'확인 필요':money(totals.actual);root.querySelector('[data-iws-dirty]').textContent=saving?'저장 중…':dirty?'저장하지 않은 변경':'저장본';root.querySelector('[data-iws-save]').disabled=saving||!dirty||calc.error;return calc;}
  function onInput(e){var el=e.target;if(el.hasAttribute('data-iws-picker')){if(saving||!allowed())return;var typed=root.querySelector('[data-iws-row="'+el.dataset.iwsPicker+'"][data-iws-field=date]');if(!typed)return;typed.value=el.value;el=typed;}var k=el.dataset.iwsField;if(!k||saving||!allowed())return;var i=Number(el.dataset.iwsRow),r=draft.rows[i];if(!r)return;if(k==='date'){var formatted=core.normalizeDate(el.value);if(formatted!==el.value)el.value=formatted;var picker=root.querySelector('[data-iws-picker="'+i+'"]');if(picker)picker.value=/^\d{4}-\d{2}-\d{2}$/.test(el.value)?el.value:'';}r[k]=k==='paid'?el.checked:el.value;if(k==='paid'&&r.paid&&!r.actual.trim()){var v=core.calculate(draft.rows).rows[i].estimate;if(!v.error){r.actual=String(v.value);root.querySelector('[data-iws-row="'+i+'"][data-iws-field="actual"]').value=r.actual;}}dirty=true;note('');refresh();}
  async function confirm(text){return window.InsuranceBriefingNotice&&window.InsuranceBriefingNotice.confirm?window.InsuranceBriefingNotice.confirm({title:'가계부 지출표',message:text,confirmLabel:'확인'}):window.confirm(text);}
  async function onClick(e){if(e.target.hasAttribute('data-iws-picker')){if(!saving&&allowed()&&typeof e.target.showPicker==='function'){e.preventDefault();try{e.target.showPicker();}catch(_){}}return;}var b=e.target.closest('button');if(!b||saving||!allowed())return;if(b.dataset.iwsMonth){month=b.dataset.iwsMonth;root.querySelector('[data-iws-select-month]').value=month;refresh();return;}if(b.hasAttribute('data-iws-save')){await save();return;}if(b.hasAttribute('data-iws-reload')){if(dirty&&!await confirm('저장하지 않은 표 변경을 버리고 저장본을 다시 불러올까요?'))return;dirty=false;draft=null;options.reload();return;}if(b.hasAttribute('data-iws-delete')){var i=Number(b.dataset.iwsDelete);if(!await confirm((i+2)+'행을 삭제할까요? 참조 중인 수식은 조정되며, 삭제한 셀 참조는 #REF!로 표시됩니다.'))return;if(!allowed()||saving)return;draft.rows=core.remove(draft.rows,i);}else{if(draft.rows.length>=core.limit){note('한 표에 최대 '+core.limit+'행까지 입력할 수 있습니다.');return;}if(b.hasAttribute('data-iws-copy'))draft.rows.push(core.copy(draft.rows,Number(b.dataset.iwsCopy),crypto.randomUUID()));else if(b.hasAttribute('data-iws-total')){if(draft.rows.some(function(r){return r.kind==='total';})){note('합계용 행이 이미 있습니다. 해당 수식을 수정하거나 표 하단 자동합계를 이용해 주세요.');return;}var t=empty('total');t.name='합계';var n=draft.rows.length+1;t.estimate=n>=2?'=SUM(C2:C'+n+')':'=0';t.actual=n>=2?'=SUM(D2:D'+n+')':'=0';draft.rows.push(t);}else if(b.hasAttribute('data-iws-add'))draft.rows.push(empty());else return;}dirty=true;render();}
  function onKey(e){if(e.key!=='Enter'||!e.target.dataset.iwsField||e.target.type==='checkbox'||saving)return;e.preventDefault();var i=Number(e.target.dataset.iwsRow)+1,k=e.target.dataset.iwsField;if(i>=draft.rows.length){if(draft.rows.length>=core.limit)return;draft.rows.push(empty());dirty=true;render();}var next=root.querySelector('[data-iws-row="'+i+'"][data-iws-field="'+k+'"]');if(next&&!next.disabled)next.focus();}
  async function save(){if(saving||!dirty||!allowed())return;var calc=core.calculate(draft.rows);if(calc.error){note('입력·수식 오류를 먼저 수정해 주세요.');return;}saving=true;root.querySelectorAll('input,button').forEach(function(e){e.disabled=true;});refresh();try{baseRevision=await options.save(JSON.parse(JSON.stringify(draft)),baseRevision);base=JSON.stringify(draft);dirty=false;note('표를 저장했습니다.');}catch(e){note(e.message+' 입력한 내용은 그대로 남아 있습니다.');}finally{saving=false;root.querySelectorAll('input,button').forEach(function(e){e.disabled=false;});root.querySelectorAll('.iws-total-row input[data-iws-field=date],.iws-total-row input[type=checkbox],.iws-total-row input[data-iws-picker]').forEach(function(e){e.disabled=true;});refresh();}}
  function mount(el,config){if(!allowed())return;root=el;options=config;var loaded=config.sheet||{version:1,rows:[]};if(!draft||(!dirty&&JSON.stringify(loaded)!==base)){draft=JSON.parse(JSON.stringify(loaded));base=JSON.stringify(loaded);baseRevision=config.revision||null;}render();}
  window.addEventListener('beforeunload',function(e){if(dirty&&allowed()){e.preventDefault();e.returnValue='';}});
  document.addEventListener('appstate:ready',function(){if(!allowed()){draft=null;dirty=false;base='';if(root)root.innerHTML='';}});
  window.OSLedgerSheet={mount:mount,sync:function(){if(root&&root.isConnected){refresh();root.querySelectorAll('.iws-total-row input[data-iws-field=date],.iws-total-row input[type=checkbox],.iws-total-row input[data-iws-picker]').forEach(function(e){e.disabled=true;});}},isDirty:function(){return dirty;}};
})();
