(function () {
  'use strict';
  var OWNER='98c5f4f9-10c1-4ee1-a656-5c2ca63239fd', KEY='personal_ledger_v1';
  var month=today().slice(0,7), rows=[], root=null, busy=false, generation=0;
  var categories=['식비','생활','교통','주거·통신','건강','여가','급여','기타'];
  function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function canSee(){try{var u=window.AppState, s=JSON.parse(localStorage.getItem('os_user')||sessionStorage.getItem('os_user')||'{}');return String(u&&u.userId||s.id||'')===OWNER&&!!(window.db&&window.db.fetch&&window.db.getToken&&window.db.getToken());}catch(_){return false;}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function valid(v){return v&&/^\d{4}-\d{2}-\d{2}$/.test(v.date)&&!isNaN(Date.parse(v.date))&&new Date(v.date).toISOString().slice(0,10)===v.date&&['income','expense'].includes(v.type)&&Number.isSafeInteger(v.amount)&&v.amount>0&&v.amount<=999999999999&&categories.includes(v.category)&&typeof v.memo==='string'&&v.memo.length<=120;}
  function total(list){return list.reduce(function(t,r){var v=r.legacy_payload.entry;t[v.type]+=v.amount;return t;},{income:0,expense:0});}
  function money(n){return n.toLocaleString('ko-KR')+'원';}
  function scope(){return 'owner_id=eq.'+OWNER+'&item_type=eq.memo&visibility=eq.private&legacy_payload->>setting_key=eq.'+KEY+'&deleted_at=is.null';}
  async function request(query,method,body){if(!canSee())throw Error('임태성 전용 화면입니다.');var options={method:method||'GET',headers:{'Content-Type':'application/json',Prefer:'return=representation'}};if(body)options.body=JSON.stringify(body);var r=await window.db.fetch('/rest/v1/insuwork_items'+query,options);if(!r.ok)throw Error('저장소에 연결하지 못했습니다. 다시 시도해 주세요. ('+r.status+')');var result=await r.json();if(!canSee())throw Error('로그인을 다시 확인해 주세요.');return result;}
  function html(){return canSee()?'<section class="iwl-page" data-iwl-page><p role="status">가계부를 불러오는 중입니다.</p></section>':'<p>임태성 전용 화면입니다.</p>';}
  function message(text){var el=root&&root.querySelector('[data-iwl-status]');if(el)el.textContent=text;}
  function monthValid(m){return /^\d{4}-(0[1-9]|1[0-2])$/.test(m||'');}
  function shiftMonth(m,n){var d=new Date(Number(m.slice(0,4)),Number(m.slice(5,7))-1+n,1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
  function dueDate(m,day){var last=new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate();return m+'-'+String(Math.min(day,last)).padStart(2,'0');}
  function amountValid(n){return Number.isSafeInteger(n)&&n>0&&n<=999999999999;}
  function dateValid(d){return /^\d{4}-\d{2}-\d{2}$/.test(d||'')&&!isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;}
  function planFields(v){return v&&typeof v.name==='string'&&v.name.trim().length>0&&v.name.length<=80&&amountValid(v.amount)&&Number.isInteger(v.day)&&v.day>=1&&v.day<=31;}
  function validPlan(p){return p&&planFields(p)&&['monthly','once'].includes(p.frequency)&&monthValid(p.start)&&(!p.end||monthValid(p.end))&&(p.frequency!=='once'||dateValid(p.date))&&Array.isArray(p.versions)&&p.versions.every(function(v){return monthValid(v.from)&&planFields(v);})&&p.paid&&typeof p.paid==='object'&&!Array.isArray(p.paid)&&Object.keys(p.paid).every(function(m){return monthValid(m)&&amountValid(p.paid[m].amount)&&dateValid(p.paid[m].date);});}
  function effective(p,m){return (p.versions||[]).filter(function(v){return v.from<=m;}).sort(function(a,b){return b.from.localeCompare(a.from);})[0]||p;}
  function projections(list,m){return list.filter(function(r){return r.legacy_payload.plan;}).map(function(r){var p=r.legacy_payload.plan,v=effective(p,m),paid=p.paid[m],active=p.frequency==='monthly'?m>=p.start&&(!p.end||m<=p.end):p.date.slice(0,7)===m;if(!active&&!paid)return null;return {id:r.id,name:v.name,estimate:v.amount,date:p.frequency==='once'?p.date:dueDate(m,v.day),paid:paid,frequency:p.frequency};}).filter(Boolean).sort(function(a,b){return a.date.localeCompare(b.date)||a.name.localeCompare(b.name);});}
  function forecastSummary(items){return items.reduce(function(t,p){t.estimate+=p.estimate;if(p.paid)t.paid+=p.paid.amount;else t.remaining+=p.estimate;t.expected=t.paid+t.remaining;return t;},{estimate:0,paid:0,remaining:0,expected:0});}
  function formField(label,name,type,value,extra){return '<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+(extra||'')+'></label>';}
  function paint(){
    paintRecords();if(!root||!root.isConnected||!canSee())return;
    // Move the existing record DOM rather than serializing it: its event handlers remain attached.
    var records=document.createElement('details');records.className='iwl-records';records.innerHTML='<summary>일반 수입·지출 기록</summary><p>기존 기록은 그대로 보존됩니다. 위 예정 지출 합계와는 별도로 집계합니다.</p>';
    var oldHead=root.querySelector('.iwl-head');if(oldHead)oldHead.remove();
    var status=root.querySelector('[data-iwl-status]');if(status)status.remove();
    while(root.firstChild)records.appendChild(root.firstChild);
    var now=today().slice(0,7),next=shiftMonth(now,1),items=projections(rows,month),sums=forecastSummary(items);
    var dashboard=document.createElement('div');dashboard.className='iwl-forecast';
    dashboard.innerHTML='<header class="iwl-head"><div><h2>가계부 · 예정 지출</h2><p>임태성 전용 · 매달 나갈 돈을 미리 확인하세요.</p></div><label>조회 월<input type="month" data-iwl-forecast-month value="'+month+'" required></label></header>'+
      '<div class="iwl-months">'+[now,next].map(function(m,i){var t=forecastSummary(projections(rows,m));return '<button type="button" data-iwl-pick="'+m+'" aria-pressed="'+(m===month)+'"><span>'+(i?'다음 달':'이번 달')+' · '+m+'</span><strong>'+money(t.expected)+'</strong><small>남은 예정 '+money(t.remaining)+' · 납부 '+money(t.paid)+'</small></button>';}).join('')+'</div>'+
      '<p class="iwl-explain">예상 총지출은 납부한 실제 금액과 미납 항목의 예상 금액을 합산합니다. 등록된 항목만 포함하며, 납부 예정월 기준입니다.</p>'+
      '<div class="iwl-totals"><article><span>'+month+' 예상 총지출</span><strong>'+money(sums.expected)+'</strong></article><article><span>납부 완료</span><strong>'+money(sums.paid)+'</strong></article><article><span>앞으로 남은 금액</span><strong>'+money(sums.remaining)+'</strong></article></div>'+
      '<div class="iwl-list-head"><h3>'+month+' 날짜별 예정 · '+items.length+'건</h3><button type="button" data-iwl-plan-refresh>새로고침</button></div><div class="iwl-list">'+(items.map(function(p){return '<article class="iwl-row"><div><small>'+p.date+' · '+(p.frequency==='monthly'?'매월 반복':'이번 한 번')+' · '+(p.paid?'납부 완료':p.date<today()?'예정일 지남 · 미납':'납부 예정')+'</small><strong>'+esc(p.name)+'</strong>'+(p.paid?'<small>'+p.paid.date+' 납부 · 예상 '+money(p.estimate)+'</small>':'')+'</div><b>'+money(p.paid?p.paid.amount:p.estimate)+'</b><div class="iwl-row-actions"><button type="button" data-iwl-pay="'+p.id+'">'+(p.paid?'납부 수정':'납부 완료')+'</button>'+(!p.paid?'<button type="button" data-iwl-plan-edit="'+p.id+'">예정 수정</button><button type="button" data-iwl-plan-stop="'+p.id+'">'+(p.frequency==='monthly'?'이달부터 중단':'예정 삭제')+'</button>':'')+'</div></article>';}).join('')||'<p class="iwl-empty">등록된 예정 지출이 없습니다. 아래에서 고정지출을 한 번 등록하면 다음 달에도 자동으로 표시됩니다.</p>')+'</div>'+
      '<form class="iwl-form iwl-plan-form"><h3 data-iwl-plan-title>예정 지출 등록</h3><input type="hidden" name="id"><label>반복<select name="frequency"><option value="monthly">매월 고정지출</option><option value="once">일회성 지출</option></select></label>'+formField('항목','name','text','','required maxlength="80" placeholder="예: 관리비"')+formField('예상 금액 (원)','amount','number','','required min="1" max="999999999999" step="1" inputmode="numeric"')+formField('매월 결제일','day','number','25','required min="1" max="31" step="1"')+formField('시작 월','start','month',month,'required')+formField('지출 예정일','date','date',month===now?today():month+'-01','required')+'<p class="iwl-form-note">31일이 없는 달은 말일로 표시합니다. 수정은 조회 중인 달부터 적용하고 지난달 예상 금액과 납부 기록은 유지합니다.</p><div class="iwl-actions"><button type="submit">예정 저장</button><button type="button" data-iwl-plan-cancel hidden>수정 취소</button></div></form><div data-iwl-payment></div><p data-iwl-status role="status" aria-live="polite"></p>';
    root.appendChild(dashboard);root.appendChild(records);
    dashboard.querySelector('[data-iwl-forecast-month]').onchange=function(e){if(!busy&&monthValid(e.target.value)){month=e.target.value;paint();}};
    dashboard.querySelectorAll('[data-iwl-pick]').forEach(function(b){b.onclick=function(){if(!busy){month=b.dataset.iwlPick;paint();}};});
    dashboard.querySelector('[data-iwl-plan-refresh]').onclick=load;
    var f=dashboard.querySelector('.iwl-plan-form');f.onsubmit=savePlan;f.elements.frequency.onchange=function(){planFormMode(f);};planFormMode(f);
    dashboard.querySelector('[data-iwl-plan-cancel]').onclick=paint;
    dashboard.querySelectorAll('[data-iwl-plan-edit]').forEach(function(b){b.onclick=function(){editPlan(b.dataset.iwlPlanEdit);};});
    dashboard.querySelectorAll('[data-iwl-plan-stop]').forEach(function(b){b.onclick=function(){stopPlan(b.dataset.iwlPlanStop);};});
    dashboard.querySelectorAll('[data-iwl-pay]').forEach(function(b){b.onclick=function(){paymentForm(b.dataset.iwlPay);};});
    if(window.OSLedgerSheet){
      var legacy=document.createElement('details');legacy.className='iwl-records';legacy.innerHTML='<summary>기존 반복 예정 지출 관리</summary><p>기존 등록 내역은 보존되며, 위 월별 요약에 함께 포함됩니다.</p>';
      root.insertBefore(legacy,dashboard);legacy.appendChild(dashboard);
      var sheetRoot=document.createElement('section');sheetRoot.className='iws-page';root.insertBefore(sheetRoot,legacy);
      var savedSheet=rows.find(function(r){return r.legacy_payload.sheet;});
      window.OSLedgerSheet.mount(sheetRoot,{sheet:savedSheet?savedSheet.legacy_payload.sheet:null,revision:savedSheet?savedSheet.legacy_payload.sheet_revision:null,legacy:function(m){return projections(rows,m);},reload:load,save:saveSheet});
    }
  }
  async function saveSheet(sheet,expectedRevision){
    if(busy||!canSee())throw Error('잠시 후 다시 시도해 주세요.');
    if(!window.OSLedgerSheetCore.valid(sheet))throw Error('표의 입력·수식 오류를 확인해 주세요.');
    var existing=rows.find(function(r){return r.legacy_payload.sheet;}),id=existing?existing.id:'a2bc12b2-5ea4-4bfd-853f-2dd80f9bd764';
    var body={owner_id:OWNER,item_type:'memo',title:'가계부 지출표',body:'',visibility:'private',legacy_payload:{workspace_category:'settings',setting_key:KEY,sheet_revision:crypto.randomUUID(),sheet:sheet}};
    if(!existing)body.id=id;
    if(existing&&existing.legacy_payload.sheet_revision!==expectedRevision)throw Error('다른 기기에서 표가 변경되었습니다. 저장본을 다시 불러온 뒤 수정해 주세요.');
    var query=existing?'?'+scope()+'&id=eq.'+encodeURIComponent(id)+'&legacy_payload->>sheet_revision=eq.'+encodeURIComponent(expectedRevision):'';
    lock(true,true);try{var saved=await request(query,existing?'PATCH':'POST',body);if(!Array.isArray(saved)||saved.length!==1)throw Error('다른 기기에서 표가 변경되었습니다. 저장본을 다시 불러온 뒤 수정해 주세요.');rows=rows.filter(function(r){return r.id!==id;});rows.push(saved[0]);return saved[0].legacy_payload.sheet_revision;}finally{lock(false);}
  }
  function planFormMode(f){var once=f.elements.frequency.value==='once';['day','start'].forEach(function(k){f.elements[k].closest('label').hidden=once;f.elements[k].required=!once;});f.elements.date.closest('label').hidden=!once;f.elements.date.required=once;}
  function planRow(id){return rows.find(function(r){return r.id===id&&r.legacy_payload.plan;});}
  function editPlan(id){if(busy||!canSee())return;var r=planRow(id);if(!r)return;var p=r.legacy_payload.plan,v=effective(p,month),f=root.querySelector('.iwl-plan-form');f.elements.id.value=id;f.elements.frequency.value=p.frequency;f.elements.frequency.disabled=true;f.elements.name.value=v.name;f.elements.amount.value=v.amount;f.elements.day.value=v.day;f.elements.start.value=p.start;f.elements.start.readOnly=true;f.elements.date.value=p.date||month+'-01';planFormMode(f);root.querySelector('[data-iwl-plan-title]').textContent=month+'부터 예정 수정';root.querySelector('[data-iwl-plan-cancel]').hidden=false;f.elements.amount.focus();}
  async function storePlan(p,r,id){var payload={workspace_category:'settings',setting_key:KEY,plan:p},body={owner_id:OWNER,item_type:'memo',title:'가계부 예정 지출',body:'',visibility:'private',legacy_payload:payload};if(!r)body.id=id;var query=r?'?'+scope()+'&id=eq.'+encodeURIComponent(r.id)+'&legacy_payload=eq.'+encodeURIComponent(JSON.stringify(r.legacy_payload)):'';var result=await request(query,r?'PATCH':'POST',body);if(!Array.isArray(result)||result.length!==1)throw Error('다른 화면에서 변경되었거나 저장 결과를 확인하지 못했습니다. 새로고침 후 확인해 주세요.');rows=rows.filter(function(x){return x.id!==result[0].id;});rows.push(result[0]);}
  async function savePlan(e){e.preventDefault();if(busy||!canSee())return;var f=e.target,r=planRow(f.elements.id.value),p=r?JSON.parse(JSON.stringify(r.legacy_payload.plan)):{frequency:f.elements.frequency.value,start:f.elements.start.value,end:'',date:f.elements.date.value,versions:[],paid:{}},v={name:f.elements.name.value.trim(),amount:Number(f.elements.amount.value),day:Number(f.elements.day.value)};if(r&&p.frequency==='monthly'){p.versions=p.versions.filter(function(x){return x.from!==month;});p.versions.push(Object.assign({from:month},v));}else{Object.assign(p,v);p.date=f.elements.date.value;if(p.frequency==='once')p.start=p.date.slice(0,7);}if(!validPlan(p)){message('항목, 예상 금액, 결제일과 시작 월을 확인해 주세요.');return;}lock(true);try{f.dataset.requestId=f.dataset.requestId||crypto.randomUUID();await storePlan(p,r,f.dataset.requestId);if(!r)month=p.start;paint();message('예정 지출을 저장했습니다.');}catch(error){message(error.message);}finally{lock(false);}}
  async function confirmAction(text){return window.InsuranceBriefingNotice&&window.InsuranceBriefingNotice.confirm?window.InsuranceBriefingNotice.confirm({title:'예정 지출',message:text,confirmLabel:'확인'}):window.confirm(text);}
  async function stopPlan(id){if(busy||!canSee())return;var r=planRow(id);if(!r)return;var p=JSON.parse(JSON.stringify(r.legacy_payload.plan));if(!await confirmAction(p.frequency==='monthly'?month+'부터 이 고정지출을 중단할까요? 지난달과 이미 납부한 기록은 유지합니다.':'이 일회성 예정 지출을 삭제할까요?'))return;if(busy||!canSee())return;lock(true);try{if(p.frequency==='monthly'){p.end=shiftMonth(month,-1);await storePlan(p,r);}else{var result=await request('?'+scope()+'&id=eq.'+encodeURIComponent(id)+'&legacy_payload=eq.'+encodeURIComponent(JSON.stringify(r.legacy_payload)),'PATCH',{deleted_at:new Date().toISOString()});if(!Array.isArray(result)||result.length!==1)throw Error('다른 화면에서 변경되었습니다. 새로고침해 주세요.');rows=rows.filter(function(x){return x.id!==id;});}paint();message('예정 지출을 정리했습니다.');}catch(error){message(error.message);}finally{lock(false);}}
  function paymentForm(id){if(busy||!canSee())return;var r=planRow(id);if(!r)return;var p=r.legacy_payload.plan,v=effective(p,month),paid=p.paid[month],box=root.querySelector('[data-iwl-payment]');box.innerHTML='<form class="iwl-form"><h3>'+esc(v.name)+' · '+month+' 납부</h3>'+formField('실제 납부 금액 (원)','amount','number',paid?paid.amount:v.amount,'required min="1" max="999999999999" step="1" inputmode="numeric"')+formField('실제 납부일','date','date',paid?paid.date:today(),'required')+'<div class="iwl-actions"><button type="submit">납부 저장</button>'+(paid?'<button type="button" data-iwl-unpay>납부 취소</button>':'')+'<button type="button" data-iwl-pay-close>닫기</button></div></form>';var f=box.querySelector('form');f.onsubmit=function(e){e.preventDefault();commitPayment(r,{amount:Number(f.elements.amount.value),date:f.elements.date.value});};box.querySelector('[data-iwl-pay-close]').onclick=function(){box.innerHTML='';};if(paid)box.querySelector('[data-iwl-unpay]').onclick=async function(){if(await confirmAction('납부 완료를 취소하고 예정 금액으로 되돌릴까요?'))commitPayment(r,null);};f.elements.amount.focus();}
  async function commitPayment(r,paid){if(busy||!canSee())return;if(paid&&(!amountValid(paid.amount)||!dateValid(paid.date))){message('실제 납부 금액과 날짜를 확인해 주세요.');return;}var p=JSON.parse(JSON.stringify(r.legacy_payload.plan));if(paid)p.paid[month]=paid;else delete p.paid[month];lock(true);try{await storePlan(p,r);paint();message(paid?'납부를 기록했습니다. 남은 예정 금액에서 제외했습니다.':'납부를 취소했습니다.');}catch(error){message(error.message);}finally{lock(false);}}
  function paintRecords(){if(!root||!root.isConnected)return;if(!canSee()){root.innerHTML='<p>임태성 전용 화면입니다.</p>';rows=[];return;}var list=rows.filter(function(r){return r.legacy_payload.entry && r.legacy_payload.entry.date.slice(0,7)===month;}).sort(function(a,b){return b.legacy_payload.entry.date.localeCompare(a.legacy_payload.entry.date)||b.id.localeCompare(a.id);}), sums=total(list);
    root.innerHTML='<header class="iwl-head"><div><h2>가계부</h2><p>임태성 전용 · 내 계정에 비공개로 저장됩니다.</p></div><label>조회 월 <input type="month" data-iwl-month value="'+month+'" required></label></header>'+
      '<div class="iwl-totals"><article><span>수입</span><strong>'+money(sums.income)+'</strong></article><article><span>지출</span><strong>'+money(sums.expense)+'</strong></article><article><span>수입 − 지출</span><strong>'+money(sums.income-sums.expense)+'</strong></article></div>'+
      '<form class="iwl-form iwl-record-form"><h3 data-iwl-form-title>내역 추가</h3><input type="hidden" name="id"><label>날짜<input name="date" type="date" value="'+today()+'" required></label><label>구분<select name="type"><option value="expense">지출</option><option value="income">수입</option></select></label><label>금액 (원)<input name="amount" type="number" inputmode="numeric" min="1" max="999999999999" step="1" required placeholder="0"></label><label>분류<select name="category">'+categories.map(function(c){return '<option>'+c+'</option>';}).join('')+'</select></label><label class="iwl-memo">내용<input name="memo" maxlength="120" placeholder="예: 점심 식사"></label><div class="iwl-actions"><button type="submit">저장</button><button type="button" data-iwl-cancel hidden>수정 취소</button></div></form>'+
      '<p data-iwl-status role="status" aria-live="polite"></p><div class="iwl-list-head"><h3>'+esc(month)+' 내역 · '+list.length+'건</h3><button type="button" data-iwl-refresh>새로고침</button></div><div class="iwl-list">'+(list.map(function(r){var v=r.legacy_payload.entry;return '<article class="iwl-row"><div><small>'+esc(v.date)+' · '+esc(v.category)+'</small><strong>'+esc(v.memo||v.category)+'</strong></div><b>'+ (v.type==='income'?'+':'−')+money(v.amount)+'</b><div class="iwl-row-actions"><button type="button" data-iwl-edit="'+esc(r.id)+'">수정</button><button type="button" data-iwl-delete="'+esc(r.id)+'">삭제</button></div></article>';}).join('')||'<p class="iwl-empty">아직 내역이 없습니다. 첫 수입이나 지출을 기록해 보세요.</p>')+'</div>';
    root.querySelector('[data-iwl-month]').onchange=function(e){if(busy)return;if(/^\d{4}-\d{2}$/.test(e.target.value)){month=e.target.value;paint();}};
    root.querySelector('.iwl-record-form').onsubmit=save;
    root.querySelector('[data-iwl-cancel]').onclick=paint;
    root.querySelector('[data-iwl-refresh]').onclick=load;
    root.querySelectorAll('[data-iwl-edit]').forEach(function(b){b.onclick=function(){if(busy||!canSee())return;var r=rows.find(function(r){return r.id===b.dataset.iwlEdit;}),v=r.legacy_payload.entry,f=root.querySelector('.iwl-record-form');f.elements.id.value=r.id;['date','type','amount','category','memo'].forEach(function(k){f.elements[k].value=v[k];});root.querySelector('[data-iwl-form-title]').textContent='내역 수정';root.querySelector('[data-iwl-cancel]').hidden=false;f.elements.amount.focus();};});
    root.querySelectorAll('[data-iwl-delete]').forEach(function(b){b.onclick=function(){remove(b.dataset.iwlDelete);};});
  }
  function lock(value,keepSheet){busy=value;if(root)root.querySelectorAll('button,input,select').forEach(function(e){if(!keepSheet||!e.closest('.iws-page'))e.disabled=value;});if(!value&&window.OSLedgerSheet)window.OSLedgerSheet.sync();}
  async function load(){if(busy||!root||!canSee())return;var ticket=++generation;lock(true);message('불러오는 중…');try{var all=[],offset=0;while(true){var part=await request('?'+scope()+'&select=id,legacy_payload&order=id&limit=500&offset='+offset);if(!Array.isArray(part))throw Error('자료 형식을 확인하지 못했습니다.');all=all.concat(part);if(part.length<500)break;offset+=500;}if(ticket!==generation)return;if(all.some(function(r){return !r.id||!(valid(r.legacy_payload&&r.legacy_payload.entry)||(validPlan(r.legacy_payload&&r.legacy_payload.plan)||(window.OSLedgerSheetCore&&window.OSLedgerSheetCore.valid(r.legacy_payload&&r.legacy_payload.sheet)&&typeof r.legacy_payload.sheet_revision==='string')));}))throw Error('확인할 수 없는 내역이 있습니다. 합계를 표시하지 않습니다.');if(all.filter(function(r){return r.legacy_payload.sheet;}).length>1)throw Error('지출표 저장본이 중복되어 확인이 필요합니다.');rows=all;busy=false;paint();}catch(e){if(root&&root.isConnected){root.innerHTML='<p role="alert">'+esc(e.message)+'</p><button type="button" data-iwl-retry>다시 시도</button>';root.querySelector('button').onclick=load;}}finally{lock(false);}}
  async function save(e){e.preventDefault();if(busy||!canSee())return;var f=e.target,id=f.elements.id.value,v={date:f.elements.date.value,type:f.elements.type.value,amount:Number(f.elements.amount.value),category:f.elements.category.value,memo:f.elements.memo.value.trim()};if(!valid(v)){message('날짜와 금액을 확인해 주세요. 금액은 1원 이상의 정수로 입력합니다.');return;}if(id&&!rows.some(function(r){return r.id===id;}))return;lock(true);message('저장 중…');try{var body={owner_id:OWNER,item_type:'memo',title:'가계부',body:'',visibility:'private',legacy_payload:{workspace_category:'settings',setting_key:KEY,entry:v}};if(!id){f.dataset.requestId=f.dataset.requestId||crypto.randomUUID();body.id=f.dataset.requestId;}var saved=await request(id?'?'+scope()+'&id=eq.'+encodeURIComponent(id):'',id?'PATCH':'POST',body);if(!Array.isArray(saved)||saved.length!==1)throw Error('저장 결과를 확인하지 못했습니다. 새로고침 후 확인해 주세요.');rows=rows.filter(function(r){return r.id!==saved[0].id;});rows.push(saved[0]);month=v.date.slice(0,7);paint();message('저장했습니다.');}catch(error){message(error.message);}finally{lock(false);}}
  async function remove(id){if(busy||!canSee()||!rows.some(function(r){return r.id===id;}))return;var ok=window.InsuranceBriefingNotice&&window.InsuranceBriefingNotice.confirm?await window.InsuranceBriefingNotice.confirm({title:'내역 삭제',message:'이 내역을 삭제할까요?',confirmLabel:'삭제'}):window.confirm('이 내역을 삭제할까요?');if(!ok||busy||!canSee())return;lock(true);try{var result=await request('?'+scope()+'&id=eq.'+encodeURIComponent(id),'PATCH',{deleted_at:new Date().toISOString()});if(!Array.isArray(result)||result.length!==1)throw Error('삭제 결과를 확인하지 못했습니다.');rows=rows.filter(function(r){return r.id!==id;});paint();message('삭제했습니다.');}catch(e){message(e.message);}finally{lock(false);}}
  function mount(){var next=document.querySelector('[data-iwl-page]');if(!next||next===root)return;root=next;rows=[];busy=false;load();}
  window._canSeeInsuworkLedger=canSee;
  window.OSInsuworkLedger={html:html,mount:mount};
  document.addEventListener('appstate:ready',function(){if(!canSee()){generation++;rows=[];if(root)root.innerHTML='';}});
})();
