(function () {
  'use strict';
  var core=window.OSLedgerSheetCore,root=null,options=null,draft=null,base='',baseRevision=null,dirty=false,saving=false,month=localMonth(),saveTimer=null,saveError='';
  var fields=['name','date','estimate','actual','paid','memo'];
  function localMonth(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
  function nextMonth(m){var d=new Date(Number(m.slice(0,4)),Number(m.slice(5))-1+1,1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function allowed(){return !!(window._canSeeInsuworkLedger&&window._canSeeInsuworkLedger());}
  function empty(kind){return {id:crypto.randomUUID(),kind:kind||'expense',name:'',date:'',estimate:'',actual:'',paid:false,memo:''};}
  function money(n){return n.toLocaleString('ko-KR')+'원';}
  function amountText(value){var s=core.addresses(String(value),-1);if(s.trim().startsWith('='))return s;var raw=s.replace(/,/g,'');if(!/^[+-]?\d+(?:\.\d*)?$/.test(raw))return s;var parts=raw.split('.');return parts[0].replace(/\B(?=(\d{3})+(?!\d))/g,',')+(parts.length>1?'.'+parts[1]:'');}
  function formatTypedAmount(el){if(el.value.trim().startsWith('='))return;var caret=el.selectionStart,prior=el.value,formatted=amountText(prior);if(formatted===prior)return;var count=prior.slice(0,caret==null?prior.length:caret).replace(/,/g,'').length,pos=0;while(pos<formatted.length&&count>0){if(formatted[pos]!==',')count--;pos++;}el.value=formatted;el.setSelectionRange(pos,pos);}
  function note(s){var n=root&&root.querySelector('[data-iws-status]');if(n)n.textContent=s;}
  function combined(calc,m){var t=core.summary(draft.rows,calc,m),old=options.legacy(m);old.forEach(function(p){t.estimate+=p.estimate;if(p.paid)t.paid+=p.paid.amount;else t.remaining+=p.estimate;});t.expected=t.paid+t.remaining;return t;}
  function monthlyHtml(calc){var year=Number(month.slice(0,4)),sum={expected:0,paid:0,remaining:0};var rows=Array.from({length:12},function(_,i){var m=year+'-'+String(i+1).padStart(2,'0'),t=combined(calc,m);Object.keys(sum).forEach(function(k){sum[k]+=t[k];});return '<tr'+(m===month?' class="iws-month-selected"':'')+'><th scope="row"><button type="button" data-iws-month="'+m+'" aria-pressed="'+(m===month)+'">'+(i+1)+'월</button></th>'+['expected','paid','remaining'].map(function(k){return '<td>'+(t.error?'확인 필요':money(t[k]))+'</td>';}).join('')+'</tr>';}).join('');return '<section class="iws-monthly" aria-label="월별 예상 지출"><div class="iws-monthly-head"><h3>월별 예상 지출 · '+year+'년</h3><div><button type="button" data-iws-month="'+(year-1)+month.slice(4)+'" aria-label="이전 연도"'+(year<=1900?' disabled':'')+'>‹</button><button type="button" data-iws-month="'+(year+1)+month.slice(4)+'" aria-label="다음 연도"'+(year>=9999?' disabled':'')+'>›</button></div></div><p>납입기한 기준 · 예상 지출 = 납부 완료 + 남은 예정 금액. 월을 누르면 위 요약이 바뀝니다.</p><div class="iws-monthly-scroll" tabindex="0" aria-label="월별 예상 지출 표 스크롤"><table><thead><tr><th scope="col">월</th><th scope="col">예상 지출</th><th scope="col">납부 완료</th><th scope="col">남은 예정</th></tr></thead><tbody>'+rows+'</tbody><tfoot><tr><th scope="row">연간 합계</th>'+Object.keys(sum).map(function(k){return '<td>'+(calc.error?'확인 필요':money(sum[k]))+'</td>';}).join('')+'</tr></tfoot></table></div></section>';}
  function summaryHtml(calc){var now=localMonth(),selected=combined(calc,month);return '<div class="iwl-months">'+[now,nextMonth(now)].map(function(m,i){var t=combined(calc,m);return '<button type="button" data-iws-month="'+m+'" aria-pressed="'+(m===month)+'"><span>'+(i?'다음 달':'이번 달')+' · '+m+'</span><strong>'+(t.error?'입력·수식 확인':money(t.expected))+'</strong><small>'+(t.error?'표의 오류를 수정하면 합계가 표시됩니다.':'남은 예정 '+money(t.remaining)+' · 납부 '+money(t.paid))+'</small></button>';}).join('')+'</div><div class="iwl-totals iws-totals">'+[['예상 총지출',selected.expected],['납부 완료',selected.paid],['앞으로 남은 금액',selected.remaining]].map(function(x){return '<article><span>'+month+' '+x[0]+'</span><strong>'+(selected.error?'확인 필요':money(x[1]))+'</strong></article>';}).join('')+'</div>';}
  function cell(r,i,key){var addr=String.fromCharCode(65+fields.indexOf(key))+(i+1),disabled=r.kind==='total'&&(key==='date'||key==='paid'),type=key==='paid'?'checkbox':'text';var input='<input data-iws-row="'+i+'" data-iws-field="'+key+'" aria-label="'+addr+' '+({name:'항목',date:'납입기한',estimate:'예정 금액',actual:'실제 납부액',paid:'납부 완료',memo:'메모'}[key])+'" type="'+type+'" '+(key==='paid'?(r.paid?'checked':''):'value="'+esc(['estimate','actual'].includes(key)?amountText(r[key]):r[key])+'" maxlength="'+(key==='memo'?300:key==='date'?10:200)+'"'+(key==='date'?' inputmode="numeric" placeholder="YYYY-MM-DD" title="숫자 8자리 입력: 20260925 → 2026-09-25 · Alt+↓ 달력 열기" aria-keyshortcuts="Alt+ArrowDown"':''))+(disabled?' disabled':'')+' autocomplete="off">';if(key==='date'){var iso=/^\d{4}-\d{2}-\d{2}$/.test(r.date)?r.date:'';input='<span class="iws-date-control">'+input+'<label class="iws-date-picker"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16"/></svg><input type="date" tabindex="-1" data-iws-picker="'+i+'" aria-label="'+addr+' 달력으로 납입기한 선택" title="달력에서 날짜 선택" value="'+esc(iso)+'"'+(disabled?' disabled':'')+'></label></span>';}if(['estimate','actual'].includes(key))input='<span class="iws-amount-control">'+input+'<span data-iws-unit="'+i+'-'+key+'" aria-hidden="true">원</span></span>';return '<td>'+input+(['estimate','actual'].includes(key)?'<output data-iws-result="'+i+'-'+key+'"></output>':'')+'</td>';}
  function render(){if(!root||!root.isConnected||!allowed())return;var calc=core.calculate(draft.rows);root.innerHTML='<header class="iwl-head"><div><h2>가계부 · 지출표</h2><p>임태성 전용 · 입력한 내용은 자동 저장됩니다.</p></div><label>요약 조회 월<input data-iws-select-month type="month" value="'+month+'"></label></header><div data-iws-summary>'+summaryHtml(calc)+monthlyHtml(calc)+'</div><p class="iwl-explain">납입기한 기준으로 표의 지출 행과 기존 반복 예정 지출을 합산합니다. 합계용 행과 일반 수입·지출 기록은 중복 집계하지 않습니다. 변경 중에는 저장 전 예상값입니다.</p>'+
      '<div class="iws-toolbar"><span data-iws-dirty role="status" aria-live="polite"></span><button type="button" data-iws-save hidden>재시도</button><button type="button" data-iws-reload hidden>내 변경 버리고 다시 불러오기</button></div><p class="iws-help">B열 납입기한: 20260925 → 2026-09-25 또는 달력 선택(Alt+↓) · C·D열: 숫자 또는 =81930+5000, =C1*3, =SUM(C1:C5) · 사칙연산과 괄호 지원 · 원 단위 반올림 · Enter 다음 행 / Tab 다음 칸 · 휴대폰에서는 표를 좌우로 밀어 편집합니다.</p>'+
      '<div class="iws-scroll" tabindex="0" aria-label="지출표 가로 스크롤"><table class="iws-table"><thead><tr><th scope="col">행 <button type="button" data-iws-add aria-label="행 추가" title="맨 아래에 행 추가">+</button></th><th scope="col">A · 항목</th><th scope="col">B · 납입기한</th><th scope="col">C · 예정 금액</th><th scope="col">D · 실제 납부액</th><th scope="col">E · 납부 완료</th><th scope="col">F · 메모</th><th scope="col">행 관리</th></tr></thead><tbody>'+draft.rows.map(function(r,i){return '<tr class="'+(r.kind==='total'?'iws-total-row':'')+'"><th scope="row">'+(i+1)+(r.kind==='total'?'<small>합계용</small>':'')+'</th>'+fields.map(function(k){return cell(r,i,k);}).join('')+'<td><button type="button" data-iws-copy="'+i+'" aria-label="'+(i+1)+'행 복사">복사</button><button type="button" data-iws-delete="'+i+'" aria-label="'+(i+1)+'행 삭제">삭제</button><small data-iws-row-status="'+i+'"></small></td></tr>';}).join('')+'<tr class="iws-add-row"><td><button type="button" data-iws-add aria-label="아래에 행 추가">+</button></td><td colspan="7"><button type="button" data-iws-add>행 추가</button><button type="button" data-iws-total>합계 행 추가</button></td></tr></tbody><tfoot><tr><th colspan="3">지출 행 자동합계</th><td data-iws-sum-estimate></td><td data-iws-sum-actual></td><td colspan="3">합계용 행 제외</td></tr></tfoot></table></div><p data-iws-status role="status" aria-live="polite"></p>';
    root.oninput=onInput;root.onfocusout=function(e){if(e.target.dataset.iwsField&&!saveError)scheduleSave(0);};root.onchange=function(e){if(e.target.matches('[data-iws-select-month]')){if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)){month=e.target.value;refresh();}}else if(e.target.type==='checkbox'||e.target.hasAttribute('data-iws-picker'))onInput(e);};root.onclick=onClick;root.onkeydown=onKey;refresh();
  }
  function refresh(){if(!root||!allowed())return;var scroller=root.querySelector('.iws-monthly-scroll'),scrollTop=scroller?scroller.scrollTop:0;var calc=core.calculate(draft.rows);root.querySelector('[data-iws-summary]').innerHTML=summaryHtml(calc)+monthlyHtml(calc);root.querySelector('.iws-monthly-scroll').scrollTop=scrollTop;var totals={estimate:0,actual:0};draft.rows.forEach(function(r,i){var v=calc.rows[i];['estimate','actual'].forEach(function(k){var el=root.querySelector('[data-iws-result="'+i+'-'+k+'"]');el.textContent=v[k].error||money(v[k].value);el.hidden=!r[k].trim().startsWith('=')&&!v[k].error;var unit=root.querySelector('[data-iws-unit="'+i+'-'+k+'"]');unit.hidden=!r[k].trim()||r[k].trim().startsWith('=')||!!v[k].error;var input=root.querySelector('[data-iws-row="'+i+'"][data-iws-field="'+k+'"]');if(document.activeElement!==input)input.value=amountText(r[k]);el.classList.toggle('iws-error',!!v[k].error);if(r.kind!=='total'&&!v.error&&!v.empty)totals[k]+=v[k].value;});var status=root.querySelector('[data-iws-row-status="'+i+'"]');status.textContent=v.error||(r.kind==='total'?'합계 집계 제외':v.empty?'':r.paid?'납부 완료':r.date<new Date().toLocaleDateString('en-CA')?'기한 지남 · 미납':'납부 예정');status.classList.toggle('iws-error',!!v.error);});root.querySelector('[data-iws-sum-estimate]').textContent=calc.error?'확인 필요':money(totals.estimate);root.querySelector('[data-iws-sum-actual]').textContent=calc.error?'확인 필요':money(totals.actual);root.querySelector('[data-iws-dirty]').textContent=saveError?'저장 실패':saving?'저장 중…':dirty?'저장 대기…':calc.error?'저장됨 · 입력·수식 확인 필요':'저장됨';root.querySelector('[data-iws-save]').hidden=!saveError;root.querySelector('[data-iws-save]').disabled=saving;root.querySelector('[data-iws-reload]').hidden=!saveError;root.querySelector('[data-iws-reload]').disabled=saving;return calc;}
  function onInput(e){var el=e.target;if(el.hasAttribute('data-iws-picker')){if(!allowed())return;var typed=root.querySelector('[data-iws-row="'+el.dataset.iwsPicker+'"][data-iws-field=date]');if(!typed)return;typed.value=el.value;el=typed;}var k=el.dataset.iwsField;if(!k||!allowed())return;var i=Number(el.dataset.iwsRow),r=draft.rows[i];if(!r)return;if(k==='date'){var formatted=core.normalizeDate(el.value);if(formatted!==el.value)el.value=formatted;var picker=root.querySelector('[data-iws-picker="'+i+'"]');if(picker)picker.value=/^\d{4}-\d{2}-\d{2}$/.test(el.value)?el.value:'';}if(['estimate','actual'].includes(k))formatTypedAmount(el);r[k]=k==='paid'?el.checked:el.value;if(['estimate','actual'].includes(k))r[k]=core.addresses(r[k],1);if(['estimate','actual'].includes(k)&&/^[+-]?[\d,]+(?:\.\d*)?$/.test(r[k]))r[k]=r[k].replace(/,/g,'');if(k==='paid'&&r.paid&&!r.actual.trim()){var v=core.calculate(draft.rows).rows[i].estimate;if(!v.error){r.actual=String(v.value);root.querySelector('[data-iws-row="'+i+'"][data-iws-field="actual"]').value=r.actual;}}dirty=true;if(!saveError)note('');refresh();scheduleSave();}
  async function confirm(text){return window.InsuranceBriefingNotice&&window.InsuranceBriefingNotice.confirm?window.InsuranceBriefingNotice.confirm({title:'가계부 지출표',message:text,confirmLabel:'확인'}):window.confirm(text);}
  async function onClick(e){if(e.target.hasAttribute('data-iws-picker')){if(allowed()&&typeof e.target.showPicker==='function'){e.preventDefault();try{e.target.showPicker();}catch(_){}}return;}var b=e.target.closest('button');if(!b||!allowed())return;if(b.dataset.iwsMonth){month=b.dataset.iwsMonth;root.querySelector('[data-iws-select-month]').value=month;refresh();return;}if(b.hasAttribute('data-iws-save')){saveError='';await save();return;}if(b.hasAttribute('data-iws-reload')){if(saving)return;if(dirty&&!await confirm('저장하지 않은 표 변경을 버리고 저장본을 다시 불러올까요?'))return;clearTimeout(saveTimer);saveError='';dirty=false;draft=null;options.reload();return;}if(b.hasAttribute('data-iws-delete')){var i=Number(b.dataset.iwsDelete);if(!await confirm((i+1)+'행을 삭제할까요? 참조 중인 수식은 조정되며, 삭제한 셀 참조는 #REF!로 표시됩니다.'))return;if(!allowed())return;draft.rows=core.remove(draft.rows,i);}else{if(draft.rows.length>=core.limit){note('한 표에 최대 '+core.limit+'행까지 입력할 수 있습니다.');return;}if(b.hasAttribute('data-iws-copy'))draft.rows.push(core.copy(draft.rows,Number(b.dataset.iwsCopy),crypto.randomUUID()));else if(b.hasAttribute('data-iws-total')){if(draft.rows.some(function(r){return r.kind==='total';})){note('합계용 행이 이미 있습니다. 해당 수식을 수정하거나 표 하단 자동합계를 이용해 주세요.');return;}var t=empty('total');t.name='합계';var n=draft.rows.length+1;t.estimate=n>=2?'=SUM(C2:C'+n+')':'=0';t.actual=n>=2?'=SUM(D2:D'+n+')':'=0';draft.rows.push(t);}else if(b.hasAttribute('data-iws-add'))draft.rows.push(empty());else return;}dirty=true;render();scheduleSave();}
  function onKey(e){if(!allowed())return;if(e.key==='ArrowDown'&&e.altKey&&e.target.dataset.iwsField==='date'){var picker=root.querySelector('[data-iws-picker="'+e.target.dataset.iwsRow+'"]');if(picker&&!picker.disabled&&typeof picker.showPicker==='function'){e.preventDefault();try{picker.showPicker();}catch(_){}}return;}if(e.key==='Tab'&&e.target.hasAttribute('data-iws-picker')){var target=root.querySelector('[data-iws-row="'+e.target.dataset.iwsPicker+'"][data-iws-field="'+(e.shiftKey?'date':'estimate')+'"]');if(target&&!target.disabled){e.preventDefault();target.focus();}return;}if(e.key!=='Enter'||!e.target.dataset.iwsField||e.target.type==='checkbox')return;e.preventDefault();var i=Number(e.target.dataset.iwsRow)+1,k=e.target.dataset.iwsField;if(i>=draft.rows.length){if(draft.rows.length>=core.limit)return;draft.rows.push(empty());dirty=true;render();}var next=root.querySelector('[data-iws-row="'+i+'"][data-iws-field="'+k+'"]');if(next&&!next.disabled)next.focus();}
  function scheduleSave(delay){clearTimeout(saveTimer);if(dirty&&!saveError&&allowed())saveTimer=setTimeout(save,delay==null?800:delay);}
  async function save(){clearTimeout(saveTimer);if(saving||!dirty||saveError||!allowed())return;var ownerDraft=draft,snapshot=JSON.parse(JSON.stringify(draft)),serialized=JSON.stringify(snapshot);saving=true;refresh();try{var revision=await options.save(snapshot,baseRevision);if(!allowed()||draft!==ownerDraft)return;baseRevision=revision;base=serialized;dirty=JSON.stringify(draft)!==serialized;note('');}catch(e){if(allowed()&&draft===ownerDraft){saveError=e.message;note(e.message+' 입력은 그대로 남아 있습니다. 재시도를 눌러 주세요.');}}finally{saving=false;if(allowed()&&draft===ownerDraft){refresh();if(dirty&&!saveError)scheduleSave();}}}
  function mount(el,config){if(!allowed())return;root=el;options=config;var loaded=config.sheet||{version:1,rows:[]};if(!draft||(!dirty&&JSON.stringify(loaded)!==base)){draft=JSON.parse(JSON.stringify(loaded));base=JSON.stringify(loaded);baseRevision=config.revision||null;}render();}
  window.addEventListener('beforeunload',function(e){if(dirty&&allowed()){e.preventDefault();e.returnValue='';}});
  document.addEventListener('appstate:ready',function(){if(!allowed()){clearTimeout(saveTimer);draft=null;dirty=false;base='';saveError='';if(root)root.innerHTML='';}});
  window.OSLedgerSheet={mount:mount,sync:function(){if(root&&root.isConnected){refresh();root.querySelectorAll('.iws-total-row input[data-iws-field=date],.iws-total-row input[type=checkbox],.iws-total-row input[data-iws-picker]').forEach(function(e){e.disabled=true;});}},isDirty:function(){return dirty;}};
})();
