/* Insurance Work editorial portal. Source files stay in the owner's private library. */
(function () {
  'use strict';
  var groups = { all: '전체', basics: '보험 이해', treatment: '질환·치료', compare: '보장 비교', underwriting: '가입·심사', history: '변천사' };
  var sources = {
    db: ['DB손해보험_솔루션북.pdf', 'DB손해보험 솔루션북'],
    meritz: ['솔루션북_메리츠화재.pdf', '메리츠화재 솔루션북'],
    technology: ['[현대해상] 알려줘 시리즈 ①신의료기술_250807_170936.pdf', '현대해상 알려줘 ① 신의료기술'],
    underwriting: ['[현대해상] 알려줘 시리즈 2.유병자보험의 모든 것.pdf', '현대해상 알려줘 ② 유병자보험'],
    cancer: ['[현대해상] 알려줘 시리즈 ③암치료보장.pdf', '현대해상 알려줘 ③ 암치료보장'],
    vascular: ['[현대해상] 알려줘 시리즈 ④ 2대질환.pdf', '현대해상 알려줘 ④ 2대질환'],
    medical: ['[현대해상] 알려줘 시리즈 5. 메디컬보장분석.pdf', '현대해상 알려줘 ⑤ 메디컬보장분석'],
    life: ['[현대해상] 알려줘 시리즈 ⑥ 생명보험체크포인트.pdf', '현대해상 알려줘 ⑥ 생명보험 체크포인트'],
    major: ['[현대해상] 알려줘 시리즈 ⑦ 3대 주요치료비.pdf', '현대해상 알려줘 ⑦ 3대 주요치료비'],
    care: ['알려줘Hi-인슈⑧간병보장.pdf', '현대해상 알려줘 ⑧ 간병보장'],
    anatomy: ['이미지_7장_2026-09-15.pdf', '2026 KB 수술비 인체도'],
    dental: ['치아보험의 모든것_라이나생명.pdf', '라이나생명 치아보험의 모든 것'],
    samsung: ['간병인지원 가이드북_삼성화재.pdf', '삼성화재 간병인지원 가이드북'],
    longcare: ['알기쉬운 노인장기 요양보험.pdf', '알기 쉬운 노인장기요양보험'],
    pet: ['펫보험의 구조', '펫보험의 구조'],
    renew: ['세대별 재가입 규정.jpg', '세대별 재가입 규정'],
    exemption: ['메리츠 예외질환 20260415.pdf', '메리츠 예외질환 · 2026.04.15'],
    driver: ['DB손해보험 운전자보험 비용담보 변천사', 'DB손해보험 운전자보험 비용담보 변천사'],
    heart: ['심혈관질환_컬러영역.png', '심혈관질환 보장 범위'],
    brain: ['뇌혈관질환_컬러영역.png', '뇌혈관질환 보장 범위']
  };
  // Descriptions are editorial reading paths, not new product/benefit determinations.
  var articles = [
    {id:'new-treatment',group:'treatment',tag:'치료를 이해하는 첫걸음',title:'치료는 달라지는데,\n내 보장은 어디까지일까?',desc:'신의료기술의 치료 방식과 수술비 담보를 함께 살펴봅니다.',visual:'technology',pages:[['technology',2,'치료 방식과 수술비 담보 비교'],['technology',3,'약관에서 말하는 수술'],['db',47,'수술의 정의를 함께 읽기']],sections:[['치료 이름에서 보장 조건까지','자료는 치료명, 질병코드, 관혈·비관혈 구분과 수술비 담보를 나란히 보여줍니다. 같은 치료라도 어떤 담보를 비교하는지 구분해서 읽습니다.'],['수술과 시술, 무엇을 확인할까?','치료의 목적과 방법을 확인하고, 가입한 특약의 수술 정의와 제외 항목을 함께 살펴봅니다. 아래 비교표는 원자료의 상품·약관 기준입니다.']],related:['surgery','cancer','vascular']},
    {id:'age',group:'basics',tag:'알쏭달쏭 보험용어',title:'생일과 보험나이는\n어떻게 다를까?',desc:'보험나이와 상령일을 그림으로 이해합니다.',visual:'db',page:4,pages:[['db',4,'보험나이와 상령일']],sections:[['보험에서 사용하는 나이','보험나이는 계약 시점의 생년월일을 기준으로 계산하는 나이입니다. 원자료는 생일로부터 6개월이 되는 시점을 중심으로 보험나이가 달라지는 흐름을 설명합니다.'],['내 날짜로 확인하기','보험워크의 보험연령표에서 생년월일을 기준으로 확인할 수 있습니다.']],tool:'insurance-age',related:['waiting','renewal']},
    {id:'waiting',group:'basics',tag:'보험금 지급의 시작',title:'면책기간과 감액기간,\n같은 뜻이 아닙니다.',desc:'보장하지 않는 기간과 일부를 지급하는 기간의 차이.',visual:'db',page:9,pages:[['db',5,'보험금 지급 흐름'],['db',9,'면책기간과 감액기간 비교']],sections:[['면책기간','가입 후 일정 기간 해당 보장이 적용되지 않는 구간을 뜻합니다.'],['감액기간','지급 사유가 생겨도 약정 보험금의 일부만 지급하는 구간입니다. 기간과 지급 비율은 가입한 상품·특약을 기준으로 확인합니다.']],related:['age','cancer']},
    {id:'renewal',group:'compare',tag:'계약 구조 비교',title:'갱신형과 비갱신형,\n비교할 것은 보험료만일까?',desc:'갱신 주기와 납입기간을 함께 놓고 읽습니다.',visual:'db',page:8,pages:[['db',8,'갱신형·비갱신형 비교']],sections:[['함께 비교할 세 가지','갱신 여부, 보험료가 산출되는 시점, 보험료 납입기간을 함께 비교합니다. 처음 내는 보험료만으로 계약 전체를 판단하지 않습니다.']],related:['silson','waiting']},
    {id:'surgery',group:'treatment',tag:'그림으로 보는 보장',title:'몸으로 찾는\n수술비 이야기',desc:'KB 수술비 인체도와 신의료기술 자료를 연결해 읽습니다.',visual:'anatomy',pages:[['anatomy',1,'KB 수술비 인체도 · 자녀'],['anatomy',2,'KB 수술비 인체도 · 두 번째 도표'],['technology',2,'신의료기술 수술비 비교'],['db',48,'생명보험·손해보험 수술비 비교']],sections:[['부위에서 시작하는 수술비 탐색','인체도의 치료명과 수술명을 먼저 찾고, 함께 표시된 담보 구성을 살펴봅니다. 인체도의 가입금액은 해당 자료의 설계 예시이며 모든 계약에 공통으로 적용되는 금액은 아닙니다.']],related:['new-treatment','vascular','dental']},
    {id:'cancer',group:'treatment',tag:'암 치료와 보장',title:'암을 진단받은 이후,\n치료 보장을 읽는 순서',desc:'암치료보장과 3대 주요치료비 자료를 함께 봅니다.',visual:'cancer',pages:[['cancer',2,'암치료보장 목차'],['cancer',3,'암 진단과 관련 용어'],['major',1,'3대 주요치료비']],sections:[['진단과 치료를 나누어 읽기','암 진단 보장, 수술·약물·방사선 등 치료 보장을 구분해 살펴봅니다. 원발암·재발암·전이암 등 자료의 용어도 함께 확인합니다.']],related:['cancer-history','new-treatment','waiting']},
    {id:'vascular',group:'compare',tag:'뇌·심장 보장 범위',title:'비슷한 담보명,\n보장 범위도 같을까?',desc:'뇌·심장 범위 그림과 2대질환 설명을 연결합니다.',visual:'vascular',pages:[['brain',1,'뇌혈관질환 범위'],['heart',1,'심혈관질환 범위'],['vascular',1,'2대질환 치료보장'],['db',34,'뇌혈관질환 특약별 보장 범위']],sections:[['담보명을 그대로 확인하기','뇌혈관질환·뇌졸중·뇌출혈처럼 구분된 이름을 유지한 채 범위 그림을 읽습니다. 심장 보장도 진단과 치료 담보를 나누어 비교합니다.']],related:['new-treatment','surgery']},
    {id:'underwriting',group:'underwriting',tag:'가입 전 살펴보기',title:'유병자보험,\n고지 질문부터 차근차근',desc:'간편심사 구조와 보험사별 예외질환 자료를 연결합니다.',visual:'underwriting',pages:[['underwriting',3,'간편심사 알릴의무 비교'],['db',37,'유병자·간편심사 보험'],['exemption',1,'예외질환 자료']],sections:[['숫자보다 질문을 먼저','간편심사 유형별로 질문하는 기간과 진료·입원·수술 등의 항목이 다릅니다. 자료의 숫자와 함께 실제 질문 문장을 읽습니다.'],['예외질환은 회사와 기준일을 함께','예외질환 자료는 회사별로 구분하고 문서의 기준일을 유지합니다. 특정 자료의 조건을 다른 회사의 인수 결과로 옮겨 적용하지 않습니다.']],related:['medical','waiting']},
    {id:'medical',group:'underwriting',tag:'의료 기록 이해',title:'메디컬보장분석,\n질환을 이해하는 출발점',desc:'알려줘 시리즈의 19개 질환 핵심요약을 읽습니다.',visual:'medical',pages:[['medical',1,'메디컬보장분석'],['db',17,'건강검진 결과 읽기'],['db',18,'건강검진 결과 읽기 · 이어서']],sections:[['건강 정보와 보험 자료 연결','질환 설명을 읽은 뒤 가입·심사 자료로 이동할 수 있습니다. 진료 기록에 적힌 용어를 이해하는 흐름으로 구성했습니다.']],related:['underwriting','vascular']},
    {id:'care',group:'treatment',tag:'돌봄과 생활',title:'간병과 장기요양,\n어떤 내용을 함께 봐야 할까?',desc:'간병보장·간병인지원·장기요양 안내를 한곳에서 읽습니다.',visual:'care',pages:[['care',1,'간병보장 알려줘'],['samsung',1,'간병인지원 가이드북'],['longcare',1,'노인장기요양보험 안내'],['db',43,'노인장기요양보험제도']],sections:[['간병 자료를 연결하는 기준','간병인지원, 간병인 사용, 간호·간병통합서비스와 장기요양을 같은 이름으로 합치지 않고 구분해 살펴봅니다.']],related:['care-history','claim']},
    {id:'claim',group:'basics',tag:'보험금 청구 준비',title:'직접 청구하기 어려울 때,\n지정대리청구인',desc:'제도의 뜻과 지정 시 확인할 내용을 읽습니다.',visual:'db',page:6,pages:[['db',6,'지정대리청구인']],sections:[['청구를 대신할 사람','보험수익자가 직접 보험금을 청구하기 어려운 사정이 생겼을 때를 대비하는 제도입니다. 대상 계약, 지정할 수 있는 사람, 지정 시기와 서류를 해당 계약 기준으로 확인합니다.']],related:['care','life']},
    {id:'life',group:'basics',tag:'생명보험 읽기',title:'CI·GI·유니버셜,\n이름에 담긴 계약의 구조',desc:'생명보험 체크포인트와 솔루션북을 연결합니다.',visual:'life',pages:[['life',1,'생명보험 보장 체크포인트'],['db',7,'CI·GI·유니버셜 용어']],sections:[['이름과 지급 조건을 함께','상품 이름만으로 보장을 판단하기보다 보험금 지급 조건과 계약 구조를 함께 읽습니다. 같은 용어를 사용해도 실제 조건은 가입한 약관을 기준으로 봅니다.']],related:['claim','renewal']},
    {id:'dental',group:'treatment',tag:'치아 보장 이해',title:'치아를 보존하는 치료와\n대신하는 치료',desc:'보존치료·보철치료의 그림과 설명을 비교합니다.',visual:'dental',pages:[['db',62,'보존치료의 종류'],['db',63,'보철치료의 종류'],['dental',1,'치아보험의 모든 것']],sections:[['치료명으로 연결하기','충전·크라운 등 보존치료와 임플란트·브릿지·틀니 등 보철치료를 구분해 살펴봅니다. 치료별 보장 조건은 가입한 치아보험의 약관과 연결해 확인합니다.']],related:['surgery','waiting']},
    {id:'driver',group:'compare',tag:'자동차와 운전자',title:'자동차보험과 운전자보험,\n나누어 살펴볼 책임',desc:'사고의 책임과 비용담보의 변화를 함께 읽습니다.',visual:'db',page:55,pages:[['db',55,'자동차보험과 운전자보험 비교'],['driver',1,'운전자 비용담보 변천사']],sections:[['보장하는 비용을 구분하기','대인·대물 배상과 형사합의·벌금·변호사선임비용을 구분해 살펴봅니다. 자료의 사고 예시와 금액은 자료 작성 당시의 예시로 읽습니다.']],related:['liability']},
    {id:'liability',group:'basics',tag:'생활 속 보장',title:'일상에서 생긴 손해,\n배상책임을 이해하기',desc:'가족일상생활배상책임과 주택화재 자료를 읽습니다.',visual:'db',page:84,pages:[['db',84,'가족일상생활배상책임'],['db',82,'화재보험 바로 알기']],sections:[['누가, 어떤 사고에 보장되는가','생활 속 사례를 통해 피보험자의 범위와 보장하는 사고를 살펴봅니다. 자기부담금과 가족의 범위는 자료의 예시를 그대로 일반화하지 않고 계약 조건을 확인합니다.']],related:['driver','pet']},
    {id:'pet',group:'basics',tag:'반려동물과 생활',title:'펫보험의 구조를\n한 장씩 살펴보기',desc:'자료실의 펫보험 설명 자료를 연결했습니다.',visual:'pet',pages:[['pet',1,'펫보험의 구조']],sections:[['원자료로 읽기','반려동물 보장 자료를 독립 주제로 연결했습니다. 자료의 설명과 도표를 확대해 읽을 수 있습니다.']],related:['liability']},
    {id:'silson',group:'history',tag:'의료실비 변천사',title:'의료실비 변천사',desc:'가입 시기부터 자기부담, 재가입까지. 세대별 변화의 흐름을 읽습니다.',visual:'renew',historyImage:'silson',history:'silson-history',pages:[],sections:[],related:['renewal','age']},
    {id:'cancer-history',group:'history',tag:'암주요치료비 변천사',title:'암주요치료비 변천사',desc:'진단비에서 치료비로, 급여에서 비급여로. 보장이 달라진 흐름을 읽습니다.',visual:'major',historyImage:'cancer',history:'cancer-treatment-history',pages:[],sections:[],related:['cancer','new-treatment']},
    {id:'care-history',group:'history',tag:'간병보험 변천사',title:'간병보험 변천사',desc:'정리된 변천사와 간병인지원 자료를 함께 연결합니다.',visual:'samsung',historyImage:'care',history:'caregiver-history',pages:[],sections:[],related:['care','claim']}
  ];
  var active='all', selected='', api=null, epoch=0, docs=new Map(), observer=null;
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function article(id){return articles.find(function(a){return a.id===id;});}
  function sourceItem(key){var def=sources[key];return def && api && api.items().find(function(i){return i.title===def[0];});}
  function route(id,category){var u=new URL(location.href);u.searchParams.set('section','insurance-portal');u.searchParams.delete('article');u.searchParams.delete('topic');if(id)u.searchParams.set('article',id);else if(category!=='all')u.searchParams.set('topic',category);history.pushState({},'',u);}
  function photo(key,page,cls){return '<div class="ip-art '+(cls||'')+'" data-ip-source="'+esc(key)+'" data-ip-page="'+(page||1)+'"><span class="ip-art-label">'+esc(sources[key]&&sources[key][1])+'</span><span class="ip-art-status" role="status">도표를 불러오는 중</span></div>';}
  function historyImage(a,cls){return '<img class="'+esc(cls||'')+'" src="/insuwork/assets/history-'+esc(a.historyImage)+'.png" alt="" loading="lazy">';}
  function teaser(id,kind){var a=article(id);return '<button class="ip-story '+(kind||'')+'" data-ip-open="'+a.id+'">'+(a.history?'<div class="ip-art ip-history-art">'+historyImage(a)+'</div>':photo(a.visual,a.page))+'<div class="ip-story-copy"><span class="ip-eyebrow">'+esc(a.tag)+'</span><h3>'+esc(a.title).replace(/\n/g,a.history?' ':'<br>')+'</h3><p>'+esc(a.desc)+'</p><span class="ip-read">읽어보기 <b aria-hidden="true">↗</b></span></div></button>';}
  function tabs(){return '<nav class="ip-tabs" aria-label="보험포털 주제">'+Object.keys(groups).map(function(k){return '<button data-ip-topic="'+k+'" aria-current="'+(active===k?'page':'false')+'">'+groups[k]+'</button>';}).join('')+'</nav>';}
  function title(k,t,p){return '<div class="ip-section-head"><div><span class="ip-eyebrow">'+k+'</span><h2>'+t+'</h2></div><p>'+p+'</p></div>';}
  function home(){return '<header class="ip-masthead"><div><span class="ip-eyebrow">INSURANCE WORK · KNOWLEDGE</span><h1>보험을 이해하는<br class="ip-mobile"> 더 넓은 시선<span>.</span></h1></div><p>치료의 변화부터 계약의 차이까지.<br>자료를 연결해, 필요한 내용을 깊이 읽습니다.</p></header>'+tabs()+(active!=='all'?'<section class="ip-topic-view">'+title('EXPLORE',groups[active],'주제에 맞춰 연결한 설명과 원자료')+'<div class="ip-story-grid">'+articles.filter(function(a){return a.group===active;}).map(function(a){return teaser(a.id);}).join('')+'</div></section>':'<section class="ip-lead" aria-label="주요 특집">'+teaser('new-treatment','ip-feature')+'<div class="ip-side-stories">'+teaser('underwriting','ip-compact')+teaser('age','ip-compact')+'</div></section><section class="ip-body-feature">'+title('VISUAL GUIDE','그림에서 시작하는 이해','치료 부위와 보장 구조를 눈으로 살펴봅니다.')+'<div class="ip-visual-row">'+teaser('surgery','ip-anatomy')+'<div class="ip-visual-links">'+teaser('vascular','ip-compact')+teaser('dental','ip-compact')+'</div></div></section><section>'+title('READ THE DIFFERENCE','비슷해 보여도, 다른 보장','계약을 읽을 때 놓치기 쉬운 차이들')+'<div class="ip-story-grid">'+['waiting','renewal','life'].map(function(id){return teaser(id);}).join('')+'</div></section><section class="ip-history-band">'+title('THEN & NOW','보험의 변화를 따라','실손 · 암주요치료비 · 간병')+'<div class="ip-history-links">'+['silson','cancer-history','care-history'].map(function(id,i){var a=article(id);return '<button data-ip-open="'+id+'"><span>0'+(i+1)+'</span><h3>'+esc(a.tag)+'</h3><p>'+esc(a.desc)+'</p><b aria-hidden="true">→</b></button>';}).join('')+'</div></section><section>'+title('LIFE & CARE','생활과 돌봄까지','치료 이후의 생활, 가족과 일상의 보장')+'<div class="ip-story-grid">'+['care','driver','liability','claim','medical','pet'].map(function(id){return teaser(id);}).join('')+'</div></section><section class="ip-series">'+title('COLLECTION','한 권의 흐름으로 읽기','주제에서 만난 내용을 원자료의 순서로 이어봅니다.')+'<div class="ip-series-list">'+[['db','85페이지'],['meritz','솔루션북'],['technology','알려줘 ①'],['underwriting','알려줘 ②'],['cancer','알려줘 ③'],['vascular','알려줘 ④'],['medical','알려줘 ⑤'],['life','알려줘 ⑥'],['major','알려줘 ⑦'],['care','알려줘 ⑧']].map(function(x){return '<button data-ip-source-open="'+x[0]+'"><span>'+esc(x[1])+'</span><strong>'+esc(sources[x[0]][1])+'</strong><b aria-hidden="true">↗</b></button>';}).join('')+'</div></section>');}
  function detail(a){return (a.history?'<div class="ip-history-detail">':'')+'<button class="ip-back" data-ip-back>← 보험포털</button><header class="ip-article-head">'+(a.history?historyImage(a,'ip-history-thumb'):'')+'<span class="ip-eyebrow">'+esc(groups[a.group])+' / '+esc(a.tag)+'</span><h1>'+esc(a.title).replace(/\n/g,a.history?' ':'<br>')+'</h1><p>'+esc(a.desc)+'</p></header><div class="ip-reading '+(a.history?'ip-history-reading':'')+'"><aside class="ip-toc"><strong>이 페이지에서</strong>'+a.sections.map(function(s,i){return '<a href="#ip-section-'+i+'">'+esc(s[0])+'</a>';}).join('')+(a.history?'<a href="#ip-history">변천사 본문</a>':'')+'<a href="#ip-originals">도표와 원자료</a><a href="#ip-related">함께 읽기</a></aside><div class="ip-article-body">'+a.sections.map(function(s,i){return '<section id="ip-section-'+i+'"><span class="ip-number">0'+(i+1)+'</span><h2>'+esc(s[0])+'</h2><p>'+esc(s[1])+'</p></section>';}).join('')+(a.tool?'<button class="ip-tool" data-ip-tool="'+a.tool+'">보험연령표에서 확인하기 →</button>':'')+(a.history?'<section id="ip-history" class="iph-native">'+((window.OSPortalHistories||{})[a.history]||'')+'</section>':'')+'<section id="ip-originals"><h2>도표와 원자료</h2><p class="ip-caption">'+(a.history?'변천사의 출처는 위 본문에 보존된 출처 표기를 확인하세요.':'각 도표는 원자료의 상품·작성 시점 기준입니다. 출처를 누르면 전체 자료를 볼 수 있습니다.')+'</p>'+a.pages.map(function(p){return '<figure>'+photo(p[0],p[1],'ip-document')+'<figcaption><div><strong>'+esc(p[2])+'</strong><span>'+esc(sources[p[0]][1])+' · '+p[1]+'페이지</span></div><button data-ip-source-open="'+p[0]+'" data-ip-page="'+p[1]+'">원본 보기 ↗</button></figcaption></figure>';}).join('')+(a.pages.length?'':'<p>위 변천사 본문의 보장 설명과 출처를 함께 확인할 수 있습니다.</p>')+'</section><section id="ip-related"><h2>함께 읽으면 좋은 내용</h2><div class="ip-related">'+a.related.map(function(id){var r=article(id);return '<button data-ip-open="'+id+'"><small>'+esc(r.tag)+'</small><strong>'+esc(r.title.replace('\n',' '))+'</strong><span>→</span></button>';}).join('')+'</div></section></div></div>'+(a.history?'</div>':'');}
  function html(){var p=new URLSearchParams(location.search);selected=p.get('article')||'';active=groups[p.get('topic')]?p.get('topic'):'all';return '<div id="iw-portal">'+(article(selected)?detail(article(selected)):home())+'<footer class="ip-footer">보험워크 보험포털 <span>개인 자료 원본을 연결한 주제별 읽기</span></footer></div>';}
  async function documentFor(key){var item=sourceItem(key);if(!item)throw new Error('자료실에서 원본을 찾지 못했습니다.');var cacheKey=key+':'+item.id;if(!docs.has(cacheKey))docs.set(cacheKey,api.url(item.id).then(async function(url){if(!/pdf/i.test(item.mime_type||item.title))return {image:url};var lib=await api.pdf();return {pdf:await lib.getDocument({url:url}).promise};}).catch(function(e){docs.delete(cacheKey);throw e;}));return docs.get(cacheKey);}
  async function paint(node,token){try{var key=node.dataset.ipSource;var d=await documentFor(key);if(token!==epoch||!node.isConnected)return;if(d.image){var img=new Image();img.alt=sources[key][1];img.src=d.image;img.onload=function(){if(node.isConnected){node.replaceChildren(img);}};img.onerror=function(){var status=node.querySelector('.ip-art-status');if(status)status.textContent='이미지를 불러오지 못했습니다.';};return;}var number=Math.max(1,Math.min(d.pdf.numPages,Number(node.dataset.ipPage)||1));var page=await d.pdf.getPage(number);if(token!==epoch||!node.isConnected)return;var natural=page.getViewport({scale:1});var width=node.classList.contains('ip-document')?Math.min(1600,Math.max(800,node.clientWidth*1.5)):680;var viewport=page.getViewport({scale:width/natural.width});var canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',sources[key][1]+' '+number+'페이지');await page.render({canvasContext:canvas.getContext('2d'),viewport:viewport}).promise;if(token===epoch&&node.isConnected)node.replaceChildren(canvas);}catch(e){if(node.isConnected){var status=node.querySelector('.ip-art-status');if(status)status.textContent=e.message||'원자료를 불러오지 못했습니다.';node.classList.add('ip-art-unavailable');}}}
  function initHistoryComparison(root){
    var full=root.querySelector('.ip-history-detail .iph-comparison');
    if(!full || full.dataset.ipCompareReady)return;
    var original=full.querySelector('table'),head=original && original.querySelector('thead tr');
    if(!head || head.children.length<3)return;
    var count=head.children.length-1;
    if(Array.from(original.rows).some(function(row){return row.cells.length!==count+1;}))return;
    full.dataset.ipCompareReady='1';full.classList.add('ip-compare-full');
    var tools=document.createElement('div');tools.className='ip-compare-tools';
    tools.innerHTML='<div class="ip-compare-modes" aria-label="비교 방식"><button type="button" data-ip-compare="pair" aria-pressed="true">선택 비교</button><button type="button" data-ip-compare="all" aria-pressed="false">전체 비교 ↔</button></div><div class="ip-compare-selectors"><label>기준 항목<select aria-label="기준 항목"></select></label><label>비교 항목<select aria-label="비교 항목"></select></label></div>';
    var pair=document.createElement('div');pair.className='ip-compare-pair';
    pair.setAttribute('role','region');pair.setAttribute('aria-label','선택한 두 항목 비교');
    var selects=tools.querySelectorAll('select'),first=selects[0],second=selects[1];
    for(var i=1;i<=count;i++){
      var label=head.children[i].cloneNode(true);label.querySelectorAll('small').forEach(function(n){n.remove();});
      first.add(new Option(label.textContent.trim(),String(i)));second.add(new Option(label.textContent.trim(),String(i)));
    }
    first.value=String(count-1);second.value=String(count);
    function renderPair(){
      var table=original.cloneNode(true),keep=[0,Number(first.value),Number(second.value)];
      table.removeAttribute('id');table.querySelectorAll('[id]').forEach(function(n){n.removeAttribute('id');});
      Array.from(table.rows).forEach(function(row){var cells=Array.from(row.cells);row.replaceChildren.apply(row,keep.map(function(index){return cells[index].cloneNode(true);}));});
      pair.replaceChildren(table);
    }
    first.addEventListener('change',function(){if(first.value===second.value)second.value=String(Number(first.value)%count+1);renderPair();});
    second.addEventListener('change',function(){if(first.value===second.value)first.value=String(Number(second.value)===1?count:Number(second.value)-1);renderPair();});
    tools.querySelectorAll('[data-ip-compare]').forEach(function(button){button.addEventListener('click',function(){
      var all=button.dataset.ipCompare==='all';
      tools.querySelectorAll('[data-ip-compare]').forEach(function(b){b.setAttribute('aria-pressed',String(b===button));});
      tools.querySelector('.ip-compare-selectors').hidden=all;pair.hidden=all;
      full.classList.toggle('is-all',all);tools.classList.toggle('is-all',all);
    });});
    full.before(tools,pair);renderPair();
  }
  function mount(bridge){api=bridge;var root=document.getElementById('iw-portal');if(!root)return;initHistoryComparison(root);epoch++;if(observer)observer.disconnect();var token=epoch;root.addEventListener('click',function(e){var b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-ip-open')){route(b.dataset.ipOpen,'all');api.render();document.getElementById('iw-main').scrollTop=0;}else if(b.hasAttribute('data-ip-topic')){route('',b.dataset.ipTopic);api.render();}else if(b.hasAttribute('data-ip-back')){route('','all');api.render();}else if(b.hasAttribute('data-ip-tool')){window.OSInsuwork.go(b.dataset.ipTool);}else if(b.hasAttribute('data-ip-source-open')){var item=sourceItem(b.dataset.ipSourceOpen);if(item)api.open(item.id,Number(b.dataset.ipPage)||1);else{b.textContent='원자료를 찾지 못했습니다';}}});observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){observer.unobserve(entry.target);paint(entry.target,token);}});},{root:document.getElementById('iw-main'),rootMargin:'240px'});root.querySelectorAll('[data-ip-source]').forEach(function(n){observer.observe(n);});}
  window.OSInsurancePortal={html:html,mount:mount,entries:function(){return articles.map(function(a){return {id:a.id,title:a.title.replace('\n',' '),description:a.desc+' '+a.tag+' '+a.sections.map(function(s){return s.join(' ');}).join(' ')};});},open:function(id){if(!article(id))return;window.OSInsuwork.go('insurance-portal');route(id,'all');if(api)api.render();}};
}());
